### ISSUE TITLE
Moodle event queue and pending assignments

### ISSUE THREAD

**Issue by jtutchings** [turnitin/moodle-mod_turnitintooltwo#112]
We have been having issues with submissions to Moodle being stuck in pending, it turns out that the Turnitintwo cron is hitting an exception and will not continue.  The message in the mdl_events_queue_handlers table is:

Handler function of component plagiarism_turnitin: s:39:"plagiarism_turnitin_event_file_uploaded"; threw exception :turnitintooltwo/Turnitin submission deletion failed. The local Moodle copy was removed but the submission in Turnitin could not be deleted.<br/><br/>Fault Code: targetreadfailure | File: /u0/webroot/virtual/cumoodle.coventry.ac.uk/www/mod/turnitintooltwo/sdk/submissionsoap.class.php | Line: 98 | Message: Error reading from database. | Code: 0
* line 668 of /mod/turnitintooltwo/lib.php: call to print_error()
* line 149 of /plagiarism/turnitin/classes/turnitin_comms.class.php: call to turnitintooltwo_print_error()
* line 2667 of /plagiarism/turnitin/lib.php: call to turnitin_comms::handle_exceptions()
* line 2239 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->delete_tii_submission()
* line 2317 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->clean_old_turnitin_submissions()
* line 2126 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->tii_submission()
* line 2681 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->event_handler()
* line ? of unknownfile: call to plagiarism_turnitin_event_file_uploaded()
* line 299 of /lib/eventslib.php: call to call_user_func()
* line 343 of /lib/eventslib.php: call to events_dispatch()
* line 450 of /lib/eventslib.php: call to events_process_queued_handler()
* line 45 of /lib/classes/task/events_cron_task.php: call to events_cron()
* line 74 of /lib/cronlib.php: call to core\task\events_cron_task->execute()
* line 61 of /admin/cli/cron.php: call to cron_run()

This appears to stop all the other submissions from being processed and so we are left with large classes of students who's assignments are stuck in pending and our teaching staff cannot mark them as no similarity reports are being generated.

John

**Comment by jmcgettrick** [comment]
Hi @jtutchings,
We fixed this in the last but one release, but the problem is that the plugin is trying to delete a file from Turnitin that has already been deleted.
The fix we implemented was to print a message to the screen and continue processing rather than fatally stopping a process which is what you're experiencing. You can see what we changed here: https://github.com/turnitin/moodle-plagiarism_turnitin/commit/ac84c96636349cbdb3f8056768c5cebb9c095486#diff-828043dc9f8d10ccd58ff8b96297794fR2708
John
