### ISSUE TITLE
Confusing resubmit text 

### ISSUE THREAD

**Issue by aspark21** [turnitin/moodle-mod_turnitintooltwo#12]
If a student has already submitted, they get a link to 'Submit Paper' this is confusing - it can be interpreted as: 1) it not having worked the first time, 2) finalising the submission, 3) adding multiple files to the submission. None of which are correct assumptions, maybe 'resubmit paper' would be better in this instance.

<img width="640" alt="screen shot 2015-10-13 at 12 17 59" src="https://cloud.githubusercontent.com/assets/4015496/10454339/de35fdc6-71ab-11e5-8064-e4043ce64aa8.png">

**Comment by amclarty** [comment]
Thanks @aspark21. We'll discuss this and reply here once we have a decision.
