### ISSUE TITLE
jQuery version conflict?

### ISSUE THREAD

**Issue by andrewrowatt-masseyuni** [turnitin/moodle-mod_turnitintooltwo#128]
Hi!

I am using a theme which loads jQuery - all good.  However, in a standard assignment activity with Turnitin enabled once a submission has been sent to Turnitin the View/grade all submissions screen does not work as expected (Edit link/button does not work, the page does not refresh when Filter settings are changed etc).  I can see the Turnitin plugin is loading jQuery v1.8.2 after the theme loads v1.11.1.  If I block v1.8.2 loading everything works per normal.

Help!! :-)

plagiarism_turnitin v2015040102

Cheers,
   Andrew

**Comment by dwinn** [comment]
Hi @andrewrowatt-masseyuni 

This sounds like a conflict with the custom theme as we have not seen this problem on our development environments. For the plugin we only develop and test against the default Moodle theme.

**Comment by dhattonturnitin** [comment]
Hi @andrewrowatt-masseyuni 
The turnitintooltwo plugin loads jQuery 1.8.2 IFF the Moodle version is 2.5 or lower, as 2.6 onwards came packaged with its own jQuery.
I've added similar logic to plagiarism_turnitin that should get released soon. In the meantime, if your workaround of blocking 1.8.2 is effective and not causing problems, then there should be no reason not to continue with that arrangement in the interim.
Kind regards
David

**Comment by dhattonturnitin** [comment]
Hi @andrewrowatt-masseyuni 
I have built in such a catch, but upon testing it started generating errors in the submission inbox. These errors are non-fatal and will only be visible with debugging switched on.
I have created issue #129 regarding these messages to flag them as a known issue.

**Comment by andrewrowatt-masseyuni** [comment]
Note: theme is:
https://github.com/moodlerooms/moodle-theme_snap

**Comment by andrewrowatt-masseyuni** [comment]
Hi David et al,

Unfortunately the blocking solution was merely used to confirm that the duplicate loading of jQuery was the issue.  I cannot use this as a workaround as the issue impacts students and teachers plus a complicating factor is that only some courses are using the alternative theme.

So, in short I do need a permanent and robust solution.  Is there anything I can do to help?

Andrew

P.S. 
I note that turnitintooltwo.js contains the line:
//var tiijq = jQuery.noConflict();

Which suggests version conflicts have been considered previously.

**Comment by dhattonturnitin** [comment]
Hi @andrewrowatt-masseyuni 
Thanks for providing us with a link to the theme. I will use it to test the changes we have made on a local environment and let you know what our results are.
Thanks
David

**Comment by andrewrowatt-masseyuni** [comment]
Thanks David!  I will pass that onto my local team.

**Comment by jmcgettrick** [comment]
Hi @andrewrowatt-masseyuni - unfortunately I don't think we are able to fix this. The plagiarism API in Moodle doesn't allow us to include jquery in the correct way so we have to use $PAGE->requires->js(). 

Does everything work ok for you still with that line removed? If so, I don't see a problem with you leaving it out.

**Comment by vsotirasqmplus** [comment]
/**
     * Load JS needed by the page.
     */
    public function load_page_components() {
        global $CFG, $PAGE;
       // replace these two lines
       // $jsurl = new moodle_url($CFG->wwwroot.'/plagiarism/turnitin/jquery/jquery-1.8.2.min.js');
        // $PAGE->requires->js($jsurl);
       // with this
        
       $PAGE->requires->jquery();
        
/plagiarism/turnitin/lib.php
