### ISSUE TITLE
Moodle 2.8 submissions do not seem to be connecting to turnitin.com server

### ISSUE THREAD

**Issue by teckgeek** [turnitin/moodle-mod_turnitintooltwo#13]
Students submit papers but the papers never seem to make it to the turnitin.com server.  In many cases a "submit to turnitin" button shows up in the assignment in place of the "submit" date, when pressed, results in this error:

 "Default exception handler: Invalid permissions detected in $CFG-&gt;dataroot directory, administrator has to fix permissions. Debug: turnitintooltwo temporary file cannot be created.\nError code: invaliddatarootpermissions\n* line 646 of /mod/turnitintooltwo/lib.php: invalid_dataroot_permissions thrown\n* line 490 of /mod/turnitintooltwo/turnitintooltwo_submission.class.php: call to turnitintooltwo_tempfile()\n* line 292 of /mod/turnitintooltwo/view.php: call to turnitintooltwo_submission->do_tii_submission()\n, referer: https://www.wcinstruction.net/fall/mod/turnitintooltwo/view.php?id=49458"

I have a ticket in to Turnitin.com (x15 days) and they have not been helpful.  

Another twist showed up yesterday where an instructor graded all of his assignments with grademark but the grades never showed up in Moodle, clicking refresh didn't bring them back, but he finally went in to the first paper to make sure that the grades were still there and then exited, then all the grades showed up.  

It screams of some type of latency or permissions issue, but I cannot for the life of me figure out exactly where the breakdown is.  This *doesn't* happen across all classrooms but it *does* happen to about 1/3 of the student submissions.  I have looked at the php logs and they pretty much say the same thing, that there are permission issues in some directory when the paper fails to send, but my dataroot permissions are set correctly and, as I said, it doesn't happen 100% of the time.

Any ideas? I am desperate for a resolution, my instructors have been patient up to now, but its mid semester and the number of submissions is growing as is the number of complaints.

Cheryl Rodriguez-
Moodle 2.8.6 LAMP installation

**Comment by jmcgettrick** [comment]
Hi @techgeek, I've responded to your support ticket this morning and believe I've solved your issue. If that is the case I'll post it on here.

**Comment by tellotello** [comment]
Any progress on this issue? Some of our users also have this problem :(

**Comment by trevor-c** [comment]
I'm also interested in this solution. We've been randomly getting the **Default exception handler: Invalid permissions detected in $CFG->dataroot directory**  error as well, though the majority of submissions work as expected. As described above, after the error is reported there is often a *Submit to Turnitin* link where the submission was attempted. Clicking this link has completed the submission in a few instances, but the post date then becomes the day/time you clicked the link, and not when the file was originally submitted.

We're on Moodle 2.8.7 in a LAMP environment.

**Comment by jmcgettrick** [comment]
The invalid permission error is because during the submission a temporary filename has been created but the filename hasn't been cleaned correctly, so if a slash was in the submission title the plugin could not get the correct file for the API request. 

This was fixed in the last release by https://github.com/turnitin/moodle-mod_turnitintooltwo/commit/f321977a648e103013ee99dc298bce43038bc303 and then https://github.com/turnitin/moodle-mod_turnitintooltwo/commit/4183f8ee7432d526da3513139f223353c19dcc20.
