### ISSUE TITLE
.dataTable .odd{background:#EFEFEF!important} conflicting with other plugins

### ISSUE THREAD

**Issue by stuartlamour** [turnitin/moodle-mod_turnitintooltwo#137]
turnitintooltwo/styles.css has the code 

.dataTable .odd{background:#EFEFEF!important} 

Is there anyway of keeping this style specific to the turnitin .dataTable?

**Comment by dwinn** [comment]
Hi @stuartlamour 

This should be possible. We'll look into it.

**Comment by stuartlamour** [comment]
brilliant - thank you!

**Comment by dhattonturnitin** [comment]
Fixed in release v2016011105

**Comment by stuartlamour** [comment]
thanks :+1:
