### ISSUE TITLE
Opening a lightbox window in assignment settings produces "M.str.turnitintooltwo is undefined"

### ISSUE THREAD

**Issue by upats** [turnitin/moodle-mod_turnitintooltwo#147]
When creating or editing an assignment's settings with turnitin enabled, when I click on one of the turnitin settings links (quickmark manager, peermark manager, rubric manager) I get an infinite spinning circle with the following javascript error "M.str.turnitintooltwo is undefined" col. 7049 turnitintooltwo.min.js

Looks like it's related to the lightbox functionality loading a popup window within the page. If you right click and open the links in a new tab, they load fine.

plagiarism plugin is version 2016011104

**Comment by jmcgettrick** [comment]
Hi @upats - this has been fixed but hasn't been released yet. There is a missing/incorrect string call here: https://github.com/turnitin/moodle-plagiarism_turnitin/pull/104/files#diff-9a8f5a8aa9f519108d314a1cd19e8e14R104. You can add this in manually if you want and this should fix the issue.

**Comment by upats** [comment]
Thanks, looks like an easy fix so I'll just do it manually for now.
