### ISSUE TITLE
Can not stop teachers from receiving submission notifications

### ISSUE THREAD

**Issue by jtutchings** [turnitin/moodle-mod_turnitintooltwo#148]
Turnitin Assignment 2 version 2016011104

Teachers are receiving submission notifications whenever a student submits to an assignment and there does not appear to be an option to turn this off.  Also users who have a manager type role at a category level are being sent the emails.

Example email
**Subject:** Submission made to assignment

A submission entitled 2 has been made to assignment REN318LON CW1 Submission: Part 1 in the class REN318LON - International Hospitality Operations Management - 1516AAA.

Submission ID: 12345678
Submission Date: 14-Mar-2016 06:24PM

**Comment by aspark21** [comment]
You can disable this by changing the default messaging outputs for "Turnitin Assignment Instructor Digital Receipt notifications" and deselecting it. Instructors an then enable it if they want to. 

It probably should  not be enabled by default.

**Comment by jtutchings** [comment]
We have this setting disabled but our staff have still been getting the emails

**Comment by jmcgettrick** [comment]
It shouldn't happen if - as @aspark21 says - you disable the instructor digital receipt notifications. If you disable emails but still keep popups enabled do the popups still send? 

For reference, the plugin defines instructors as users who are able to grade so that will in reality encompass a number of roles.

**Comment by jtutchings** [comment]
Thanks for your replies.
We have actually ended up setting it as "Disallowed" as all other configurations didn't stop the emails unfortunately I had a new report this morning that the emails are being sent out.

When I check the users message settings that are reporting the emails they have all been set not to receive the emails.  My only option for the ones that have been receiving lots of the emails is to temporary disable notifications, which is not perfect as they will no longer get any messages out of Moodle.

**Comment by aspark21** [comment]
@jmcgettrick Same as @jtutchings for us too actually, we went from setting the default to not send, now to disallowed and we are still getting notifications being sent to teachers. Could it be the turnitin website sending them instead?

**Comment by aleksmacheta** [comment]
We just updated Turnitin Assignment 2 version 2016011104 in our Production environment this morning and are noticing the same issue.
We have had to 'Disallow' Turnitin Assignment Instructor Digital Receipt notifications.  However our Instructors are still receiving notifications each time a student submits!  

Our workaround has been to advise all Instructors to edit their messaging settings manually and untick pop-up and email notifications for:

Turnitin Assignment Digital Receipt notifications
Turnitin Plagiarism Plugin Digital Receipt notifications
Turnitin Assignment Non Submitter notifications

We don't want to untick these at a global level since students rely on getting email submission notifications.

**Comment by aleksmacheta** [comment]
In addition, the documentation (https://guides.turnitin.com/03_Integrations/Turnitin_Partner_Integrations/Moodle/Moodle_Direct_V2/Direct_V2_Integration_Administrator_User_Manual/Enabling_Student_Submission_Notifications) states that 
"As an administrator, you can choose whether a notification is automatically sent to instructors when a student has made a submission to an assignment. This allows instructors to keep track of submissions and act on late submissions to an assignment. **This setting is set to No by default.** By enabling this feature, instructors will receive a Moodle notification, which can be accessed from their Moodle inbox.".
It actually seems to be set to YES by default.

**Comment by Syxton** [comment]
Another issue is the line in turnitintooltwo_submission.class.php ~line 630:
$this->submission_instructors = get_users_by_capability($context,'mod/turnitintooltwo:grade', 'u.id');

This will retrieve all users that have this ability at this context...however that includes site admins and managers.  The better code would be:

$this->submission_instructors = get_enrolled_users($context,'mod/turnitintooltwo:grade', 0, 'u.id');

This then limits the returned users as having to have an active enrollment in the course and cuts off users that have system permissions that would satisfy the original code.

**Comment by rlorenzo** [comment]
@Syxton A better solution might be to just email those listed as Tutors and not just get anyone with the grade capability. One of the developers at our University is working on such a patch.

**Comment by jbriggscmet** [comment]
We just experienced the same issue. Changing notification settings made no difference.

The list of message outputs defined for the plugin are (from https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/v2016011105/db/messages.php):
* submission
* nonsubmitters
* notify_instructor_of_submission

`instructor_message.php` gives the message name as `submission`, surely this should be `notify_instructor_of_submission`? See https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/v2016011105/classes/digitalreceipt/instructor_message.php#L42.

**Comment by cwestgarth** [comment]
Hi @jbriggscmet, @rlorenzo, @aleksmacheta, @Syxton, @jtutchings, @aspark21  

Thank you all for your input and raising this with us. I will pass this onto the Engineering Team to investigate further.

Regards 
Caroline Westgarth 
(Product Manager, Turnitin)

**Comment by VladimirSavitchi** [comment]
Hi, we've just updated to v2016011105 and found that notifications are being sent to all the tutors.
Regardless that the group of the student with the tutor is different.

**Comment by davidmhatton** [comment]
Hi @VladimirSavitchi, we are aware of the plugin behaviour whereby every tutor is emailed and are currently working on addressing it. thanks for reporting.

**Comment by haietza** [comment]
A workaround for this is to leave the default message outputs for email configured to Permitted, then to disable the individual user message preferences for Turnitin Email (user profile -> administration -> preferences -> messaging).

**Comment by cb526** [comment]
Is there any progress on this? We would not have updated had we known of this issue.

**Comment by cwestgarth** [comment]
Hi @cb526,

We have fixed the issue but we have yet to release the version of the plugin containing the fix. We will look to release within the next month.  

Thanks

**Comment by whymiss** [comment]
Please hurry. Many people are getting angry at hundreds of emails being received one by one.

**Comment by aspark21** [comment]
@cwestgarth What's up with the release schedule? Usually there's a monthly release like clockwork but there hasn't been one in 3 months. Is it because of the work on the migration tool from V1?

**Comment by cwestgarth** [comment]
Hi @aspark21 the team here in the UK have been working on a broader project over the last couple of months. We are looking to release in the next couple of weeks which will include support for Moodle 3.1. 

Thanks

**Comment by aspark21** [comment]
👍

**Comment by sharpchi** [comment]
Just want to add another scenario: for our department administrators we give them the grading capability (as this is the only way they can view TII submissions) at the category level (i.e. we assign "dept admin" role at the category).

![manage category](https://cloud.githubusercontent.com/assets/3774280/16692042/18a0115a-4527-11e6-8407-107227385fac.png)

They are not explicitly enrolled on the Moodle courses (i.e. not listed in the user list), but they still get an email. If a user is not enrolled on a Moodle course they shouldn't really be getting these emails.

**Comment by cwestgarth** [comment]
Hi @sharpchi, 

Thank you for raising this with us. As we only have three roles in Turnitin we acknowledge anyone who has the permission to grade an assignment as an instructor. We therefore enrol them in Turnitin as an instructor. This is why they are receiving the email.

**Comment by sharpchi** [comment]
Thanks for replying @cwestgarth, I understand what you're saying, the distinction we're making is that these people are not enrolled on the course, so perhaps they shouldn't be enrolled in Turnitin.

**Comment by cwestgarth** [comment]
Thank you @sharpchi and apologies for the inconvenience.
I will create a ticket for our engineering team to look into further.
Many thanks.

**Comment by aspark21** [comment]
@cwestgarth is the pull request for the fix public? I don't think I saw it but if not any chance it could be?
Or is there any chance the new version will be released by Tuesday? 

We are scheduled to be upgrading our main site to 3.0 Wednesday, if this isn't ready we are going to have to cancel our upgrade...with little hope of having a new slot anytime soon.

I also had not realised that this would be triggering the processing of the email notifications backlog to teachers as other institutions have found out during their upgrades. We can't be going through that again.

**Comment by hitteshahuja** [comment]
@cwestgarth does this affect the plagiarism plugin too for moodle 3?

**Comment by cwestgarth** [comment]
Hi @hitteshahuja, 
This affects the Plagiarism Plugin too. 

Thanks

**Comment by hitteshahuja** [comment]
@cwestgarth Can you please confirm when this is due to be fixed ( even if on a "develop" branch which can be ported through) . We upgrade to 3.0.4 in a week or so and this will have a high impact on our academic community.

**Comment by cwestgarth** [comment]
Hi @hitteshahuja 
We are hoping to get the fix out in the next couple of weeks, at the very latest.

Thanks

**Comment by cwestgarth** [comment]
Hi @hitteshahuja, 

Apologies we currently do not have this feature available in the Plagiarism plugin yet. Please disregard the comment above. 

Thanks

**Comment by hitteshahuja** [comment]
@cwestgarth So it does not affect the Plagiarism plugin then?

**Comment by cwestgarth** [comment]
Hi @hitteshahuja 
No this won't affect the PP.

Thanks

**Comment by dwinn** [comment]
This has now been fixed in the latest release v2016072601.

**Comment by ishanivardhan** [comment]
Just needed to check if the feature to avoid sending notifications to tutors of different groups was ever implemented? Is there a setting in place where we specify which tutor should get notifications OR tutors of which particular group should get notifications?
