### ISSUE TITLE
Submissions fail when file extension in CAPS

### ISSUE THREAD

**Issue by mkpelletier** [turnitin/moodle-mod_turnitintooltwo#159]
I am getting submission failures for assignments with file extensions in CAPS.  For example, I receive this error:
You must upload a supported file type for this assignment. Accepted file types are; .doc, .docx, .ppt, .pptx, .pps, .ppsx, .pdf, .txt, .htm, .html, .hwp, .odt, .wpd, .ps and .rtf

For this file: BIB2125 Assessment 1 2016.PDF

Should the file names not be case insensitive?  Furthermore, on occasion a student will upload some file with no extension or a . in the filename, however the mime information is still available in the metadata.  Moodle reads these just fine, but Turnitin does not.  Could we not revise the way the filetypes are assessed in these cases?

**Comment by jmcgettrick** [comment]
We'll get that looked at @mkpelletier

**Comment by dwinn** [comment]
This has now been fixed in the latest release v2016072601.
