### ISSUE TITLE
Turnitin Breaking Moodle Cron

### ISSUE THREAD

**Issue by mjk7** [turnitin/moodle-mod_turnitintooltwo#16]
Hi. I am getting the following error when the moodle cron runs.

>Processing module function turnitintooltwo_cron ...
>... used 337 dbqueries
>... used 57.634557008743 seconds
>Scheduled task failed: Legacy cron processing for plugins,Error reading from database
>Default exception handler: Error reading from database Debug: MySQL server has gone away
>SELECT * FROM mdl_task_scheduled WHERE classname = ?
>[array (
>  0 => '\\core\\task\\legacy_plugin_cron_task',
>)]
>Error code: dmlreadexception
>* line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
>* line 1080 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
>* line 1476 of /lib/dml/moodle_database.php: call to >mysqli_native_moodle_database->get_records_sql()
>* line 1448 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
>* line 1427 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
>* line 577 of /lib/classes/task/manager.php: call to moodle_database->get_record()
>* line 91 of /lib/cronlib.php: call to core\task\manager::scheduled_task_failed()
>* line 61 of /admin/cli/cron.php: call to cron_run()

>!!! Error reading from database !!!

>Debug info: MySQL server has gone away
>SELECT * FROM mdl_task_scheduled WHERE classname = ?
>[array (
>  0 => '\\core\\task\\legacy_plugin_cron_task',
>)]
>Error code: dmlreadexception
>Stack trace: * line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
>* line 1080 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
>* line 1476 of /lib/dml/moodle_database.php: call to >mysqli_native_moodle_database->get_records_sql()
>* line 1448 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
>* line 1427 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
>* line 577 of /lib/classes/task/manager.php: call to moodle_database->get_record()
>* line 91 of /lib/cronlib.php: call to core\task\manager::scheduled_task_failed()
>* line 61 of /admin/cli/cron.php: call to cron_run()
>PHP Fatal error:  Uncaught exception 'coding_exception' with message 'Coding error detected, it >must be fixed by a programmer: \core\lock\lock() has fallen out of scope without being released.
>Locks must ALWAYS be released by calling $mylock->release().' in /data/moodle/lms/public_html
>/lib/classes/lock/lock.php:107
>Stack trace:
>#0 [internal function]: core\lock\lock->__destruct()
>#1 {main}
>  thrown in /data/moodle/lms/public_html/lib/classes/lock/lock.php on line 107

Was wondering if you had a suggestion for fixing the issue? The cron not running is causing us a variety of issues.

**Comment by amclarty** [comment]
@mjk7,+ I use MySQL too and haven't seen this error before.

In the query that appears to be failing, does '\core\task\legacy_plugin_cron_task' exist in your mdl_taskl_scheduled table?

What version of MySQL are you using?

**Comment by mjk7** [comment]
We are using moodle 2.8, Redhat 7, mariadb

>In the query that appears to be failing, does '\core\task\legacy_plugin_cron_task' exist in your mdl_taskl_scheduled table?

Yes.

**Comment by amclarty** [comment]
@mjk7, I have the latest version of Moodle 2.8 using MariaDB. I've ran through our automation and manually tested submitting and running the cron and haven't found any errors.

The error in your stack trace  - "!!! Error reading from database !!! Debug info: MySQL server has gone away" - seems to be a common one in the Moodle tracker.

**Comment by mjk7** [comment]
Bummer. Well TY for taking a look at it.

**Comment by amclarty** [comment]
@mjk7, let us know how you get on. If you're stuck and you think it's the plugin causing the issue go ahead and raise a support request. With login details for your Moodle environment we can troubleshoot further. Good luck!
