### ISSUE TITLE
Scheduled task (cron) fails when TurnItIn rows exist without a course module

### ISSUE THREAD

**Issue by jbriggscmet** [turnitin/moodle-mod_turnitintooltwo#164]
For some reason we have a number of TurnItIn activities in the turnitintooltwo table which have no matching entry in course_modules. I can only assume that the plugin (or possibly older versions of it) doesn't remove the row from turnitintooltwo when an activity is deleted.

This is causing the scheduled task to fail with the error "Invalid course module ID". Should be a simple case of ensuring `$cm` is not equal to false before continuing in https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/v2016011105/lib.php#L608.

**Comment by dwinn** [comment]
Hi @jbriggscmet 

Thanks for the report.

I'm unable to replicate that scenario using the latest version (activities appearing in turnitintooltwo table with no matching entry in course_modules table) so I think your suspicion that it could be down to older versions not cleaning up after themselves on deletion may be correct.

I have managed to replicate the error through manual database deletion to simulate a missing entry in course_modules table for a turnitintooltwo entry and I see the error you describe.

We will get this fixed and look into the code change you suggested.

**Comment by dwinn** [comment]
This has now been fixed in the latest release v2016072601.
