### ISSUE TITLE
Feature request: access limitation for lecturers/teachers within single Turnitin assignment.

### ISSUE THREAD

**Issue by mwehr** [turnitin/moodle-mod_turnitintooltwo#170]
Hi,

At our university of applied science we have a variety of different usages of the turnitin assignment/activity.
Most of the departments are using one Moodle course for the final exams. Because some exams themes are under an NDA, we need additional access restrictions for those academic works (master theses).
Our current solution is to create multiple turnitin activities and add roles and limit rights in the assignments to grant the specific supervisor full access but only to their corresponding turnit assignments, e.g, 20 supervisors equals 20 turninit assignments in one Moodle course.

Another possibility would be to add a special mode to the turnitin module. If this mode is active a student which submits his document aka final exam via turnitin also has to select one or more users/supervisor with "lecturer/teacher" role.
This user(s) are stored in relation to the submitted document. 
Example: Lecturer A supervisors Students 1, 2, and 3; Lecturer B supervises Students 4,5, 6
All students upload their master theses to one Turnitin assignment and in the new feature select their supervisor as well. Thus, Lecturer B can only access the similarity reports and download the original document from St. 4,5 and 6.

So supervisors with lecturer/teacher roles only can open documents via the turnitin module if they are selected in the submission process but they should only be able to access their students' turnitin similarity reports.

We are aware that this feature does not limited those users who can access turnitin directly but we want to limit access via the Moodle plug-in.

Please share any experience or opinions if this feature could be useful.

regards,

Mario

**Comment by jmcgettrick** [comment]
Sorry, this doesn't fit with Turnitin's current workflow.
