### ISSUE TITLE
Helpdesk wizard issues

### ISSUE THREAD

**Issue by sam-moodle** [turnitin/moodle-mod_turnitintooltwo#172]
We use this activity for our customer sites (thanks!!) and as part of that review the plugin for inclusion into our code base. When I reviewed the most recent version I noticed that the new helpdeskwizard class is not namespaced and so could potentially cause namespace collisions. I think the other classes may have the same problem. I didn't want to change them in case I missed a usage somewhere.

I also noticed that the output from generated from the XML file that is not cleaned at all. I understand that it is coming from Turnitin via SSL, but "never trust any input", right. :) I made some changes locally to our instance to escape the solution "issue" (using s()) and formatted the answer using format_text() and clean the link with clean_param() using the PARAM_URL constant. I'm not sure this is the exact right fix so I thought I'd report it here to see what you thought.

Thanks for looking at this and if I can clarify anything, please let me know. And thanks for the plugin!

**Comment by jmcgettrick** [comment]
Hi @sam-moodle, could you make a pull request of your changes to the develop branch and we'll look at getting them in to the plugin.
