### ISSUE TITLE
Query for turnitin to support global search

### ISSUE THREAD

**Issue by Lina-LI-Na** [turnitin/moodle-mod_turnitintooltwo#178]
Hi John. Many thanks for providing this plugin to the community; its functionality is really appreciated by our staff and students, and we’re really grateful to you for your efforts to maintain and update it.

On that note, please could I quickly query whether you have any plans to update the plugin to be fully compatible with Moodle v3.1, and its new Global Search feature in particular? To clarify: while we’ve tested the Turnitin’s Moodle Direct v2 integration plugin under v3.1 and all of the core functionality seems to work fine, we’ve found that instances of the activity are not searchable via v3.1’s Global Search feature. Please see the following screenshot for details, which lists all of the available areas that can searched under v3.1 (note that these settings are available via: Site Administration -> Plugins -> Search -> Manage Global Search):

http://imgur.com/lWWQByE

Note also that the above screenshot was taken on a v3.1 system where the Turnitin’s Moodle Direct v2 integration plugin is installed and available. However, as you can see, the Turnitin’s Moodle Direct v2 integration activity is not listed as being available to be searched. Obviously, this is likely to be a significant problem/cause of confusion for users who might want to search for specific instances of the Turnitin’s Moodle Direct v2 integration activity across Moodle.

I’m not a developer, but my understanding is that mod plugins can be made searchable relatively easily via the addition of a new search class within the plugin’s codebase (located at ../classes/search/activity.php). Please see the following for further details:

https://moodle.org/mod/forum/discuss.php?d=334938
https://docs.moodle.org/31/en/Global_search
https://docs.moodle.org/dev/Search_API

We really hope this search capability can be added to Turnitin’s Moodle Direct v2 integration as I’m sure it would be a huge benefit to our users (as well as those of other v3.1 systems) and, again, many thanks for all your efforts to develop this plugin and share it with the community.

Best wishes,
Lina

**Comment by jmcgettrick** [comment]
Hi Lina, 
Thanks for the information, this is something we will investigate and hope to include as soon as we can.
Regards
John

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
