### ISSUE TITLE
Apilog and Activitylog now deleted daily, used to be available for eight days

### ISSUE THREAD

**Issue by alexumn** [turnitin/moodle-mod_turnitintooltwo#185]
Sometime between v2015040102 and v2015040111, the Turnitin API log (mod/turnitintooltwo/settings_extras.php?cmd=apilog) and Activity log (mod/turnitintooltwo/settings_extras.php?cmd=activitylog) changed from being available for eight days, down to being deleted every day.

Can you explain why this change was made? 

We'd like to raise this limit back to its previous value to help with troubleshooting, since student/instructor reports of issues can take a few days to come in. 

Worth noting: We exclusively use the Turnitin PP plugin, but these logs appear in the Turnitin Assignment 2 settings, so I'm asking here.

**Comment by dwinn** [comment]
Hi @alexumn,

The plugin is designed to keep the latest 10 logs and we have not changed this.

The code for deletion is in lib.php. You can see [here](https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/v2015040111/lib.php#L139-L156) in version v2015040111 that the deletion is still set as 10 and I can confirm that it still is in the latest version as well. This is not something we would decide to change as logging is important for us too.

**Comment by alexumn** [comment]
This was due to a misconfigured "Delete stale temp files" (\core\task\file_temp_cleanup_task) setting.
