### ISSUE TITLE
Post date and hidden until behavior seems buggy

### ISSUE THREAD

**Issue by ericmerrill** [turnitin/moodle-mod_turnitintooltwo#186]
At Moodlerooms, we received a user report that the hidden until date seemed to be 'broken'. The behavior they specifically noted was that after you created a turnitin assignment, the grade items hidden until date is set, but if you edit the grade item, and on that page try to change that date, or disable it, it always reverts back to the previous setting. But, if on the gradebook setup screen you click show from the quick action menu, it will stick as shown (until the grade item is updated by something, in which case it will re-hide). Note that this is in Moodle 3.0.

While the general behavior is by design, we identified a few things that probably add to the confusion:
1. I find 'Post date' to have no meaning - I had to look it up. Maybe this needs to be renamed, at least in US english (Maybe it means something in the UK?)
2. The 'Post date' field has no help icon with it.
3. There is no way to disable post date (and hence 'hidden until'). That being said, I don't know if it is required to be a valid date by the Turnitin API.
4. The dataflow is always from the Turnitin assign Post date to the grade item hidden until field. Modifying the hidden settings of the grade items will always (eventually) get overridden by the assign setting.

**Comment by cwestgarth** [comment]
Hi @merrill-oakland,

Thank you for feeding this back. We are aware of this issue (https://github.com/turnitin/moodle-mod_turnitintooltwo/issues/56).  

Unfortunately the change to the hidden until date is outside of the control of the plugin, we therefore have no way of knowing a change has been made. We could look to querying any change  when a user opens up the assignment inbox, however there still could be a potential gap from when the post date was amended in Moodle to when they post date is updated in Turnitin.

Thanks.

**Comment by merrill-oakland** [comment]
I *think* there is an event fired for changes to the grade item, so you should use an event observer to detect the changes.

**Comment by carl-hostrander** [comment]
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.
