### ISSUE TITLE
Error on fullname function

### ISSUE THREAD

**Issue by haietza** [turnitin/moodle-mod_turnitintooltwo#192]
On submitting a Turnitinassignment, debugging reveals the following:

You need to update your sql to include additional name fields in the user object.
line 3269 of /lib/moodlelib.php: call to debugging()
line 193 of /mod/turnitintooltwo/turnitintooltwo_submission.class.php: call to fullname()
line 69 of /mod/turnitintooltwo/turnitintooltwo_submission.class.php: call to turnitintooltwo_submission->get_submission_details()
line 268 of /mod/turnitintooltwo/view.php: call to turnitintooltwo_submission->__construct()

See https://docs.moodle.org/dev/Additional_name_fields#The_fullname_function for information on updated way to call fullname().

**Comment by dwinn** [comment]
Hi @haietza,
Thanks for the report. We will look into updating our calls on the function to include the extra fields.

**Comment by jmcgettrick** [comment]
Fixed in v2016091401.
