### ISSUE TITLE
Lang string missing: emailnonsubmitters

### ISSUE THREAD

**Issue by steveorulez** [turnitin/moodle-mod_turnitintooltwo#199]
Hello,
We just installed version 2016072601

if you click on "Notify Non-Submitters" there is a missing string in the popup
[[emailnonsubmitters]]

![selection_077](https://cloud.githubusercontent.com/assets/4101369/17327264/27951036-58b7-11e6-9b3d-0d951212c4cf.png)

**Comment by dwinn** [comment]
Hi @steveorulez,

Thanks for pointing this out. We will get it fixed in the next version. It seems to be named messagenonsubmitters in the language string file so it is inconsistent with the code where it is being called.

**Comment by jmcgettrick** [comment]
Fixed in v 2016091401
