### ISSUE TITLE
File picker issue when submitting paper

### ISSUE THREAD

**Issue by jbriggscmet** [turnitin/moodle-mod_turnitintooltwo#20]
A number of our staff and students are experiencing issues with the file picker dialog when attempting to submit a paper. On smaller screens, the file picker does not resize correctly. This appears to be a result of the submit paper dialog being rendered within an IFrame:

![capture](https://cloud.githubusercontent.com/assets/15365068/10794807/9f4a37dc-7d8e-11e5-8e31-eae55b0395af.PNG)

Within other areas of Moodle the dialog resizes correctly, filling 100% of the screen width and height:

![non_tii_fullscreen](https://cloud.githubusercontent.com/assets/15365068/10794806/9f48703c-7d8e-11e5-93e4-04a5e8062d11.PNG)

I have tested this out on Chrome 46.0.2490.80 on a Window 7 desktop. Other users have a similar setup. A resolution to this issue would be much appreciated.

**Comment by amclarty** [comment]
Hi @jbriggscmet ,

Thanks for raising this. Making the plugin responsive is something we’re currently investigating. We know the Submission Inbox needs some development to work well across different devices and smaller resolutions.

I had a look in Firefox and Chrome developer tools (the same version you reported) and I can’t replicate your issue:

Firefox:
![firefox_upload_a_file](https://cloud.githubusercontent.com/assets/8697035/10814705/6674c3d2-7e1f-11e5-9028-230704c83f41.png)

Chrome:
![chrome_upload_a_file](https://cloud.githubusercontent.com/assets/8697035/10814728/880c9c5e-7e1f-11e5-95f2-7ac5052a450f.png)

I note you have a “MoodleData” section which I don’t have.

Can you let me know:

* the steps you’re taking to get to the misaligned modal
* your Moodle version
* your plugin version
* your screen resolution

And I'll try to reproduce.

Thanks,

Alex.

**Comment by jbriggscmet** [comment]
Thanks for the prompt reply @amclarty 

I am simply resizing the browser window, the issue seems to occur with a window width of around 1010px and below. My screen resolution is 1920x1080, although this is happening on other screens with a smaller resolution (such as 1440x900):

![chrome_inspector](https://cloud.githubusercontent.com/assets/15365068/10815851/89ecf58a-7e26-11e5-8602-53a53584a81a.PNG)


The issue seems to be related to a missing CSS class on the modal. Outside of TII the following CSS is applied:

![fullscreen_css](https://cloud.githubusercontent.com/assets/15365068/10815833/6c305e24-7e26-11e5-9e76-fa46bc98c444.PNG)

However the file picker in the submit paper dialog is missing it:

![tii_css](https://cloud.githubusercontent.com/assets/15365068/10815849/84b81b94-7e26-11e5-9f57-d1e89f5a62c4.PNG)


We are using Moodle 2.8.7 with turnitintooltwo plugin version 2015040106.

Thanks

**Comment by amclarty** [comment]
Thanks, @jbriggscmet. I'll raise a ticket internally and we'll get this looked at. Hopefully we'll have some news soon about making the plugin work a little nicer on smaller resolutions and different devices too.

**Comment by jbriggscmet** [comment]
Thanks @amclarty. I'll keep an eye out for updates on here.

**Comment by jmcgettrick** [comment]
Hi @jbriggscmet, is this issue still occurring? We've looked at it a few times and are hvaing no joy in reproducing the problem.

**Comment by jbriggscmet** [comment]
It appears to be resolved now. We haven't had any further complaints from users following an upgrade to 2015040111.

**Comment by jmcgettrick** [comment]
Thanks. Great to hear.
