### ISSUE TITLE
Check for $CFG->version before using

### ISSUE THREAD

**Issue by micaherne** [turnitin/moodle-mod_turnitintooltwo#202]
The test for the Moodle version number in version.php causes a PHP notice to be thrown when $CFG->version is not set (e.g. when running unit tests):

> Notice: Undefined property: stdClass::$version in F:\htdocs\mod\turnitintooltwo\version.php on line 33

It would be good to test for this property's existence before using it.

This was fixed in the plagiarism plugin (https://github.com/turnitin/moodle-plagiarism_turnitin/pull/142) but is still an issue in the latest mod release.

**Comment by dwinn** [comment]
Hi @micaherne ,

Thanks for reporting the issue. We will change it to be consistent with PP.

**Comment by jmcgettrick** [comment]
Implemented in 2016091401
