### ISSUE TITLE
Submission Inbox Orders by First Name

### ISSUE THREAD

**Issue by davidmhatton** [turnitin/moodle-mod_turnitintooltwo#204]
The submission inbox inherits the Moodle settings for full-name display, but the submission inbox table sorts the entries by the literal string in the name column. 

Thus where the full-name display is _firstname surname_ the inbox will order the rows by firstname/surname, which is inconsistent with Moodle's surname/firstname.

**Comment by jmcgettrick** [comment]
Fixed in v2017052401
