### ISSUE TITLE
V2 not supporting multiple rubrics for multi part assignments

### ISSUE THREAD

**Issue by willmaltby** [turnitin/moodle-mod_turnitintooltwo#21]
With the V1 dropbox it was possible to create a multi part assignment and set a different rubric for each part.

With V2, despite the improved Rubric manager, it now only possible to attach 1 rubric to the whole assignment, not individual parts.

So would it be possible to add in this functionality please?

**Comment by jmcgettrick** [comment]
Hi @willmaltby 
This currently isn't possible through v2 but is definitely something that is feasible. The first step would be to make a suggestion on uservoice: http://turnitin.com/en_us/resources/blog/424-product/2040-roadmap-and-release-notes which will make our Product Management department aware of the desire for this.

**Comment by cwestgarth** [comment]
Hi @willmaltby, 
Thank you for raising this with us. We will certainly look into this to see whether this is something which we can implement. 
Thanks 
Caroline

**Comment by willmaltby** [comment]
Thanks for getting back to me.

I've now made a post on uservoice.

Cheers.
