### ISSUE TITLE
Suspended students appear in Assignment inbox

### ISSUE THREAD

**Issue by jmcgettrick** [turnitin/moodle-mod_turnitintooltwo#212]
It's recently come to our attention that students who are suspended in Moodle still show up in the assignment inbox. This is something we will look to rectify.

**Comment by rlorenzo** [comment]
Submitted patch as part of https://github.com/turnitin/moodle-mod_turnitintooltwo/pull/217

**Comment by dwinn** [comment]
This has been fixed in the latest release v2017012501
