### ISSUE TITLE
Feature request - E-mail notifications to specific lecturers

### ISSUE THREAD

**Issue by luiz1361** [turnitin/moodle-mod_turnitintooltwo#216]
Hi all,

I would like to request a feature to allow the administrator to select which enrolled lecturers should receive e-mail notifications about student's assignment submissions. 
At the moment all lecturers enrolled on a module get notifications about new submissions, however in some situations not all of them should get notifications about the submissions. This is true when Course Administrator are enrolled to a module due to inheritance.

**Comment by cwestgarth** [comment]
HI @luiz1361,

Thank you for passing this on. I will discuss this internally to see if this is something which we can implement. 

Regards 

Caroline

**Comment by luiz1361** [comment]
Hi Caroline,

I really appreciate it.
