### ISSUE TITLE
Grade value is always 100 points - can't be changed

### ISSUE THREAD

**Issue by cytochromec** [turnitin/moodle-mod_turnitintooltwo#238]
Adding or Editing a turnitin assignment allows for a point value to be set, but the Moodle gradebook sets them all to be 100 points (which is the default max grade in the turnitin settings for our site). The value can't be edited in the Moodle gradebook and editing the point value in the turnitin assignment doesn't change the value in the gradebook. Moodle version 2.9

**Comment by amclarty** [comment]
@cytochromec, thanks for raising this.

Grade value can be changed in Moodle in the Grade section:

![screenshot Moodle Grade](https://cloud.githubusercontent.com/assets/8697035/21612093/a013c2da-d1c7-11e6-982f-2f576cc16813.png)

However this only applies to the Gradebook and not the Turnitin assignment. The way we deal with grades between Moodle and Turnitin is a little confusing and I think we can improve it. I'm going to raise this with the team and I'll reply with an update as soon as I can.
