### ISSUE TITLE
Papers not processed

### ISSUE THREAD

**Issue by ianmcn** [turnitin/moodle-mod_turnitintooltwo#239]
Hi

We've had an issue for a long time where a small number of submitted papers would be stuck in pending and not open in document viewer, usually giving an M14:11 error. All it would take to fix is for the teacher or administrator to download the originally submitted file and reupload it. The second time it would always work. We had reported this to support, but never got anywhere with a solution. We probably get about 100 papers a year that have this issue.

Recently I think we've found the cause of the issue, and it's due to functionality that exists in Turnitin but without having the corresponding UI in the Moodle integration. If we check the broken submission from Turnitin.com we see an exclamation mark warning the teacher of unusual word usage patterns. If we click the explanation mark, it immediately allows access to the paper through document viewer. 
![1](https://cloud.githubusercontent.com/assets/2265103/20967183/7d633dc8-bc97-11e6-970b-31b8fc77dfbd.jpg)

The problem is, through moodle this explanation mark feature doesn't exist, even though the underlying functionality does. This results in an inadequate user experience, because opening the flagged paper just gives an indecipherable error message. If it's not possible to implement the exclamation mark feature in Moodle, is it possible to stop Turnitin from flagging these papers when submitted via the integration?

**Comment by sharpchi** [comment]
Yes, this smells very much like our issue. Thanks for the info.

**Comment by amclarty** [comment]
@ianmcn, @sharpchi - thanks for raising.

This is something we're currently investigating for the V2 plugin. 

We're currently building these features into our LTI integration, if that helps?

I'll post here once we've investigated inclusion in the V2 plugin.

**Comment by sharpchi** [comment]
We'd be keen to see this fix coming through in V2. We're not particularly keen on LTI integrations as they generally don't have as good UX as native integrations - especially on mobiles.

Thanks for responding.
Mark

**Comment by ianmcn** [comment]
@amclarty 
Thanks for the reply Alex, it's good to finally understand the cause of these indecipherable error messages. I think Turnitin should be considering this as a bug rather than a missing feature, because the lacking feature on one side of the integration is not matched on the other side, producing a broken experience for some users. If the flagging feature could be switched off at the turnitin end that would be fine, or if the exclamation feature could be added to the integration that would also solve it, but the current mismatch in features is an issue that needs resolving.
