### ISSUE TITLE
Turnitin Support Wizard embeds insecure iframe

### ISSUE THREAD

**Issue by rlorenzo** [turnitin/moodle-mod_turnitintooltwo#240]
When using the Turnitin Support Wizard, if you click on "No, I Need More Help" it tries to load an insecure page (http) in an iframe. If the website is secure (https) the frame is blocked from loading on modern web browsers (like Chrome). Either the more help should open in new window or load a secure version of the page in the iframe.

**Comment by amclarty** [comment]
@rlorenzo, thanks for raising this. I've raised this internally and will let you know the outcome.

**Comment by rlorenzo** [comment]
Just a note, this is still a problem with the latest 2017070301 of the plugin.
