### ISSUE TITLE
Overall grade not updating when overridden in grade book

### ISSUE THREAD

**Issue by amandadoughty** [turnitin/moodle-mod_turnitintooltwo#246]
From my user:
We have an assignment that is using a scale called 'Civil Engineering Coursework receipts', set in the Grade settings in the Turnitin assignment with the ratings On Time/Late.

The scale marking was applied in the Gradebook. Take for example Keith he was initially given a Late (2) and then this was updated to On time (1). The initial scale of Late went through to Turnitin, but it is not accepting the updated scales from the Gradebook.

![gradebook](https://cloud.githubusercontent.com/assets/4435897/21680267/a05dbdca-d340-11e6-900d-7535794a2bdb.png)
![tiigrade](https://cloud.githubusercontent.com/assets/4435897/21680268/a05e2f3a-d340-11e6-9715-07099979fdd2.png)
![late](https://cloud.githubusercontent.com/assets/4435897/21680269/a05ee560-d340-11e6-9220-e9950d273fc6.png)
![scale](https://cloud.githubusercontent.com/assets/4435897/21680270/a05f3dd0-d340-11e6-9ef5-3cd4afc048dc.png)

**Comment by jmcgettrick** [comment]
Hi, is the grade being updated within the Gradebook? The grade in the Turnitin Assignment inbox is calculated when the inbox is loaded from the numeric grade value stored in the database. If a grade is changed in the Gradebook then it isn't posted back to the Turnitin Assignment so it won't update.
