### ISSUE TITLE
Refresh submissions not updating gradebook

### ISSUE THREAD

**Issue by deanmaunder** [turnitin/moodle-mod_turnitintooltwo#251]
Clicking the 'Refresh Submissions'
![image](https://cloud.githubusercontent.com/assets/2639446/22234423/d76190c8-e243-11e6-8de0-d734b17b45b6.png)
 in the TII Assignment module updates the content on the page, but does not update the grade book.
Clicking the 'per student refresh' 
![image](https://cloud.githubusercontent.com/assets/2639446/22234427/e9b7f6fe-e243-11e6-94d2-4673123f43d4.png)
button updates the students grade in Moodle

**Comment by jmcgettrick** [comment]
The refresh submissions button only refreshes submissions that have been modified in Turnitin since the last refresh. There is a timestamp stored in the database that is updated on refresh.

**Comment by dwinn** [comment]
In the latest release, v2017031301 we have implemented a new feature to force a refresh within the assignment settings page. This will update the gradebook for all submissions.
