### ISSUE TITLE
New User Password

### ISSUE THREAD

**Issue by haleyngonadi** [turnitin/moodle-mod_turnitintooltwo#258]
Hi. 

TurnItIn is beautifully creating new users through the API. The only issue is when the users go to TurnItIn to login for the first time, their moodle password doesn't work. Is there a default password being set? Without logging in, the users aren't able to probably submit assignments as it keeps throwing an ECLA agreement error.

**Comment by jmcgettrick** [comment]
Hi @haleyngonadi, the password being set is random. What is the agreement error users are seeing?

**Comment by haleyngonadi** [comment]
Thank you. How does the user know the password if it is random? Can it get emailed to them to reset the password at any point?

Here are the agreement errors. 

![agreement error](https://cloud.githubusercontent.com/assets/6877114/22594129/be9d86b0-e9ef-11e6-8cb2-39fefefdefcb.png)
![turnitin](https://cloud.githubusercontent.com/assets/6877114/22594128/be9c151e-e9ef-11e6-9433-5d9ac2ea12a7.png)

**Comment by jmcgettrick** [comment]
They aren't supposed to know their password as it's for the Turnitin website. Integrations users (students anyway) shouldn't really need to access Turnitin through the website.

Can you contact support regarding the User not found error and we will gather some more data from you.
