### ISSUE TITLE
#eadff4944 causing cannot write to database errors

### ISSUE THREAD

**Issue by sk-unikent** [turnitin/moodle-mod_turnitintooltwo#273]
In function "update_submissions_from_tii", a submission is read from Tii and for whatever reason the submission_objectid in the Moodle DB does not match what is in the Tii data.
This causes a duplicate submission_hash for two separate submission_objectid, which save_updated_submission_data sees as an insert and subsequently fails to write to the DB.

This means Tii for most modules is currently completely broken as noone can submit or view the inboxes.

**Comment by sk-unikent** [comment]
See https://github.com/turnitin/moodle-mod_turnitintooltwo/commit/eadff4944#diff-3ba712d05df7febf4cd268e3740877f5

**Comment by jmcgettrick** [comment]
This looks like you have an assignment where a user has more than one submission. Can you double check this through the native website please?

**Comment by sk-unikent** [comment]
It looks to me like the code is faulty, the SQL in the upgrade scripts checks against: userid, turnitintooltwoid, submission_objectid
But every hash generated is against $submission->userid.'_'.$submission->turnitintooltwoid.'_'.$submission->submission_part.

Seems like the hash should be $submission->userid.'_'.$submission->turnitintooltwoid.'_'.$submission->submission_objectid?

**Comment by sk-unikent** [comment]
update_submissions_from_tii is getting two submissions from turnitin for this user, but surely the code should be able to handle it?

**Comment by sk-unikent** [comment]
Or should the upgrade SQL be grouped / checked on partid instead of objectid?

**Comment by brianlmerritt-kent** [comment]
A Turnitin case has been raised for this - number 00596845. Please confirm asap that someone is working on this thanks!

**Comment by jmcgettrick** [comment]
Hi @brianlmerritt-kent - I've been in contact with @sk-unikent this morning, we'll get this fixed asap.

**Comment by brianlmerritt-kent** [comment]
?Great - please copy me in thanks

________________________________

**Comment by dwinn** [comment]
This has been fixed in the latest release, v2017031301.
