### ISSUE TITLE
'Update this Turnitin Assignment' button unavailable

### ISSUE THREAD

**Issue by Naomi-Mifsud** [turnitin/moodle-mod_turnitintooltwo#276]
Hi,

We have recently updated Moodle Direct v2 from v2016072601 to the latest v2017022201, and noticed that the 'Upgrade this Turnitin Assignment' button, which is usually located top-right corner, is no longer available.

Kindly, do you know whether this is intentional or a bug?

Thanks,
Naomi

**Comment by jmcgettrick** [comment]
Hi, it has been deprecated by Moodle from 3.2 onwards so we've removed it.
