### ISSUE TITLE
Debug error message when reminder is sent

### ISSUE THREAD

**Issue by ebithell** [turnitin/moodle-mod_turnitintooltwo#333]
Steps to reproduce in Moodle 3.2.3, plugin version 2.7+ (occurs only with debugging enabled):
- Create a Turnitin Direct V2 assignment
- Enrol 2 or more students
- 1 student submits
- Notify non-submitters

The messages/emails are sent successfully, but a debug warning/error message is issued:
[turnitin_debug.txt](https://github.com/turnitin/moodle-mod_turnitintooltwo/files/1040916/turnitin_debug.txt)

I suspect that this is related to [MDL-47162](https://tracker.moodle.org/browse/MDL-47162)

**Comment by jmcgettrick** [comment]
Yes this was sorted in a previous release: https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/develop/classes/nonsubmitters/nonsubmitters_message.php#L49
