### ISSUE TITLE
Upgrade step for duplicated submissions is slow

### ISSUE THREAD

**Issue by rlorenzo** [turnitin/moodle-mod_turnitintooltwo#346]
We are upgrading to 2017011301 and the upgrade process on our PROD server is taking over an hour now.

https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/master/db/upgrade.php#L181

The query appears to very inefficient for large number of records.

**Comment by rlorenzo** [comment]
For some reason the query is not completing. It took longer than 4 hours on our PROD server until we had to kill it and it is running on my dev instance of our PROD server for 18 hours now.

**Comment by jmcgettrick** [comment]
We'll take another look at this @rlorenzo if it's causing problems. The point of it is to remove any  submission rows in the database that may have been duplicated. We'll see if there is another way to do this.

**Comment by rlorenzo** [comment]
For now we just commented out the upgrade code where it does the query. Note, that the upgrade seemed to work fine on  5.5.56-MariaDB. Just not 5.5.56-log - MySQL Community Server (GPL).
