### ISSUE TITLE
Error message text contrast makes it unreadable for some users

### ISSUE THREAD

**Issue by NeillM** [turnitin/moodle-mod_turnitintooltwo#36]
The error message when a user cannot submit a file to Turnitin has a very low contrast between the text and back ground. this makes it difficult to read for some users:

![error-message](https://cloud.githubusercontent.com/assets/1038050/11266387/1f577142-8e9c-11e5-97b1-1167bd84c611.PNG)

This was taken in Moodle 2.7.11 with the Clean theme, version 2015040110 of turnitintooltwo

**Comment by jmcgettrick** [comment]
Hi Neill, we'll get this changed.

**Comment by jmcgettrick** [comment]
This has been rectified in 2016011101
