### ISSUE TITLE
Unit test failure in latest 3.3 with turnitintooltwo version:2017080901

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-mod_turnitintooltwo#366]
1) core_calendar_container_testcase::test_delete_module_delete_events
Undefined property: stdClass::$apiurl

/var/www/html/mod/turnitintooltwo/turnitintooltwo_comms.class.php:39
/var/www/html/mod/turnitintooltwo/turnitintooltwo_user.class.php:213
/var/www/html/mod/turnitintooltwo/turnitintooltwo_user.class.php:193
/var/www/html/mod/turnitintooltwo/turnitintooltwo_user.class.php:49
/var/www/html/mod/turnitintooltwo/turnitintooltwo_assignment.class.php:677
/var/www/html/mod/turnitintooltwo/lib.php:284
/var/www/html/mod/turnitintooltwo/lib.php:270
/var/www/html/course/modlib.php:124
/var/www/html/lib/testing/generator/module_generator.php:267
/var/www/html/calendar/tests/container_test.php:362
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

**Comment by danmarsden** [comment]
I think this could be fixed by adding something like the following code to the top of lib.php function turnitintooltwo_edit_instance()

if (defined('BEHAT_SITE_RUNNING')) {
		set_config('apiurl', 'http://invalid', 'turnitintooltwo');
		set_config('accountid', '1001', 'turnitintooltwo');
		set_config('secretkey', 'ABCDEFGH', 'turnitintooltwo');
}

**Comment by danmarsden** [comment]
wrong check - it's unit tests not behat so something like this:
(defined('PHPUNIT_TEST') && PHPUNIT_TEST)

**Comment by danmarsden** [comment]
nope - those ideas weren't quite right - have submitted a pull request that fixes it for us.

**Comment by dwinn** [comment]
Hi @danmarsden,

Thanks for the pull request, we will take a look at this.

**Comment by dwinn** [comment]
Hi @danmarsden,

I merged your pull request and have been testing it but the unit test is still failing, but with a different error.

`1) core_calendar_container_testcase::test_delete_module_delete_events
dml_write_exception: Error writing to database (ERROR:  null value in column "dateformat" violates not-null constraint
DETAIL:  Failing row contains (210001, 187000, 0, Turnitin Assignment 2 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, Test turnitintooltwo 1, 0, 0, 0, 0, null, null, null, null, null, null, null, null, 0, 0, 0, 1, 25, 0, 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0).
INSERT INTO phpu_turnitintooltwo (course,name,intro,introformat) VALUES($1,$2,$3,$4) RETURNING id
[array (
  'course' => '187000',
  'name' => 'Turnitin Assignment 2 1',
  'intro' => 'Test turnitintooltwo 1',
  'introformat' => '0',
)])

/usr/share/nginx/html/lib/dml/moodle_database.php:489
/usr/share/nginx/html/lib/dml/pgsql_native_moodle_database.php:242
/usr/share/nginx/html/lib/dml/pgsql_native_moodle_database.php:886
/usr/share/nginx/html/lib/dml/pgsql_native_moodle_database.php:934
/usr/share/nginx/html/mod/turnitintooltwo/turnitintooltwo_assignment.class.php:697
/usr/share/nginx/html/mod/turnitintooltwo/lib.php:284
/usr/share/nginx/html/mod/turnitintooltwo/lib.php:270
/usr/share/nginx/html/course/modlib.php:124
/usr/share/nginx/html/lib/testing/generator/module_generator.php:267
/usr/share/nginx/html/calendar/tests/container_test.php:362
/usr/share/nginx/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit core_calendar_container_testcase calendar/tests/container_test.php`

I then added the lines you suggested for `lib.php` however these attempt to call Turnitin on a host that it can't resolve. I don't think Moodle unit tests should be trying to call Turnitin.

With that said, we'll continue looking at a fix as we'd like to put this in the next release.

**Comment by dwinn** [comment]
I can get the test to pass by modifying your changes slightly:

```$turnitintooltwo->id = $DB->insert_record("turnitintooltwo", $turnitintooltwo);
$toolid = $DB->insert_record("turnitintooltwo", $this->turnitintooltwo);
return $toolid;```

becomes just:

```$turnitintooltwo->id = $DB->insert_record("turnitintooltwo", $turnitintooltwo);
return $turnitintooltwo->id;```

And by ensuring $config->accountid is set during unit testing in backup_turnitintooltwo_stepslib.php

**Comment by danmarsden** [comment]
Looks like a typo in my patch with $this->turnitintooltwo - that should definitely be $turnitintooltwo - in our test history that patch worked fine last week but I'm now seeing the same issue you are this week - probably just some weird behaviour that allowed it to work previously. 

I see you haven't fixed that in the develop branch yet, I'll test your change here and file a new pull request.

**Comment by danmarsden** [comment]
fun... now the tests are failing because the same core test deletes the activity which triggers recycle bin which tries to take a backup of the turnitin assignment which triggers an error because accountid is blank. Will try to hack around that too....

1) core_calendar_container_testcase::test_delete_module_delete_events
Undefined property: stdClass::$accountid

/var/www/html/mod/turnitintooltwo/backup/moodle2/backup_turnitintooltwo_stepslib.php:83
/var/www/html/backup/util/plan/backup_structure_step.class.php:88
/var/www/html/backup/util/plan/base_task.class.php:181
/var/www/html/backup/moodle2/backup_activity_task.class.php:222
/var/www/html/backup/util/plan/base_plan.class.php:178
/var/www/html/backup/util/plan/backup_plan.class.php:120
/var/www/html/backup/controller/backup_controller.class.php:322
/var/www/html/admin/tool/recyclebin/classes/course_bin.php:125
/var/www/html/admin/tool/recyclebin/lib.php:151
/var/www/html/course/lib.php:1184
/var/www/html/calendar/tests/container_test.php:371
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

**Comment by dwinn** [comment]
Hi @danmarsden,

Yeah I didn't get the testing finished earlier today in the office so I didn't commit anything yet. I encountered that second issue with the $accountid as well; the solution is to ensure $config->accountid has a value (for just unit testing) in backup_turnitintooltwo_stepslib.php. I will most likely make a commit to develop tomorrow so don't worry about it!

**Comment by danmarsden** [comment]
cool - thanks!

**Comment by dwinn** [comment]
Hi @danmarsden,

I've just fixed this in commit which is now in develop:
https://github.com/turnitin/moodle-mod_turnitintooltwo/commit/a54032bda6054e8b1dc6d5d8894e5dd407faa5c4

Please try it out on your end.

**Comment by danmarsden** [comment]
thanks @dwinn - ran latest dev branch on our systems and I get green traffic lights :smiley:
