### ISSUE TITLE
TURNITIN notification sent to users who enrollment has expired

### ISSUE THREAD

**Issue by mileginy** [turnitin/moodle-mod_turnitintooltwo#373]
We has encountered the TURNITIN notification sent to the user (role : tutor) who enrollment has expired. 

Can you please check and modify so the users who enrollment has expired won't receive any TURNITIN notification? 

Thank you.
![screencapture](https://user-images.githubusercontent.com/25074507/30838874-c0985070-a2a0-11e7-96a9-df313177de2f.png)

**Comment by cwestgarth** [comment]
Hi @mileginy, 
Closing the issue for now, we're going to add this fix to our updated version of the V2 plugin.

Thank you
