### ISSUE TITLE
unused function dummy_api_url() and unkind use of test.com

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-mod_turnitintooltwo#391]
looks like this was initially planned to generate a dummy apiurl but it makes a reference to $DB->get_record without calling global $DB so won't work..

but I think this has been replaced with this line anyway:
https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/master/tests/unit/turnitintooltwo_comms_test.php#L43

which uses the api url "http://www.test.com"

test.com is a real site and anyone running Turnitin unit tests will be generating invalid traffic to their site.

you should be using a Turnitin domain or one of the special-use domains:
https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml

I'm not sure that in this case you should be using example.com because although it is a special-use domain it contains a valid site and it might not be ideal to be sending invalid traffic their way if possible.

**Comment by dwinn** [comment]
Hi @danmarsden,

Thanks, we will take a look at this.

**Comment by dwinn** [comment]
Hi @danmarsden,

We have just released v2017103001 with this fix.
