### ISSUE TITLE
Modal size issues on upload pop up

### ISSUE THREAD

**Issue by daparker26** [turnitin/moodle-mod_turnitintooltwo#4]
Hi John,

Sorry to leave yet another issue. Since upgrading to v2015040109 (and possibly before), the modal window that pops up when a student uploads an assignment is significantly smaller than I think is intended. I checked the code in turnitintooltwo.js under the initializeUploadBox function, and it sets the width and height for the modal at 80%; however, in my browser the upload modal is 700px x 90px. I've tried adjusting the code to pixels, and there is still no change, so I'm not sure if that is actually the code that is affecting the modal.

I'm using Moodle 2.6.6 with a theme that is largely based on bootstrap. I don't think it is interfering with the plugin, but I could be wrong.

Any suggestions for a fix? Thanks!

**Comment by richheath** [comment]
We were experiencing this issue. We found we could clear it with a clear of all the caches in Moodle, and a clearing of the browser cache. Annoying, but worked every time for us!

**Comment by daparker26** [comment]
@richheath Thank you! That worked for me.

**Comment by jmcgettrick** [comment]
Glad that worked, thanks @richheath. We've had a couple of users mention the same issue but we haven't been able to reproduce it, I was under the impression that Moodle purged all caches when upgrading plugin versions.

**Comment by richheath** [comment]
No worries. Moodle does purge all the caches, so I think it's more the browser cache, but can't hurt to do it again! I'm guessing it was actually the js file that was being cached by the browser, rather than css. I don't think Moodle caches the js itself, instead leaving it up to the browser (but I could be wrong!).
