### ISSUE TITLE
Incorrect grading information for block overview

### ISSUE THREAD

**Issue by dmitriim** [turnitin/moodle-mod_turnitintooltwo#404]
To replicate the issue:

On the Turnitin assignment submission page: Select the blue pen for an 'un-marked' submission, then close the Turnitin feedback studio page without adding a grade. 

Go and check course overview block on  the main page 'You have Turnitin Assignments that need attention' (per screenshot attached). It indicates that the submission has been 'Graded', even though you only viewed the paper and didn't add a grade.

![image](https://user-images.githubusercontent.com/4626431/33251119-23214076-d389-11e7-9b3f-99aebafaffe4.png)

![image](https://user-images.githubusercontent.com/4626431/33251132-37f30110-d389-11e7-89c1-ad31b36343ee.png)

![image](https://user-images.githubusercontent.com/4626431/33251145-44375534-d389-11e7-977a-bea88b52f25c.png)

**Comment by egiles** [comment]
Hi

So, I have just noticed that there is a pull request that will solve this issue - pull#405 ...

It really looks like there is a real issue here, and it looks like there has been a solution to it available for more than a year...  Is there any chance of getting this merged in please?
