### ISSUE TITLE
Calendar events for the new myoverview.

### ISSUE THREAD

**Issue by mfabriczy** [turnitin/moodle-mod_turnitintooltwo#407]
Hi,

May I suggest adding Turnitin assignment events to the new [overview](https://docs.moodle.org/33/en/Course_overview) block.

I'm currently developing this as a customisation for a client and hope to submit a pull request here shortly.

**Comment by cwestgarth** [comment]
Hey @mfabriczy 

Thank you for the suggestion. We are currently working on giving the Moodle Direct V2 plugin a refresh and this is something which we have included. 

We'll notify you when we're releasing the updated plugin. 

Thank you 

Caroline Westgarth
Product Manager, Integrations
Turnitin

**Comment by mfabriczy** [comment]
Thanks for the update Caroline.

**Comment by CharlotteSpinks** [comment]
Available in most recent plugin versions, bug fixed in latest release of v2019070201
