### ISSUE TITLE
Plugin CSS overriding Moodle nav CSS

### ISSUE THREAD

**Issue by sarahjcotton** [turnitin/moodle-mod_turnitintooltwo#421]
The following margin is overriding the Moodle navigation CSS. Brute force isn't the best way of doing things.

.dropdown-menu {
    white-space: nowrap;
    **margin-top: 2px !important;**
}

**Comment by rlorenzo** [comment]
This is addressed in this pull request: https://github.com/turnitin/moodle-mod_turnitintooltwo/pull/414

We ran into the same issue and hope the next version includes this patch.

**Comment by rlorenzo** [comment]
Just noting that although the pull request https://github.com/turnitin/moodle-mod_turnitintooltwo/pull/414 is closed as fixed, the style still exists in the newest version of the plugin: v2019050101

https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/06523a923a37466717008964d3ad56ead7d8d76f/sass/partials/_inbox.scss#L86

**Comment by jmcgettrick** [comment]
Sorry for the confusion, the PR was closed because of conflicts with styles.css.map and it was easier to make the changes from our end. The changes have been made to develop in #532 and we'll get them out soon.

**Comment by rlorenzo** [comment]
@jmcgettrick Although this pull request was closed, the fix was not implemented. In v2019050101 the . dropdown-menu style is still in the global namespace. See https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/develop/sass/partials/_inbox.scss#L87
