### ISSUE TITLE
Unit test failure in latest turnitintooltwo version

### ISSUE THREAD

**Issue by pauldamiani** [turnitin/moodle-mod_turnitintooltwo#424]
Getting the following error when running unit tests:

There was 1 error:

1) mod_turnitintooltwo_v1migration_testcase::test_check_account_ids
Undefined property: stdClass::$accountid

/mod/turnitintooltwo/classes/v1migration/v1migration.php:699
/mod/turnitintooltwo/tests/unit/classes/v1migration/v1migration_test.php:974
/lib/phpunit/classes/advanced_testcase.php:80

Seems like db inserts are being used instead of set_config so the cache is not being updated.

**Comment by pauldamiani** [comment]
Created a pull request for a solution that fixes the issue for me on Moodle 3.0 / Totara 9

**Comment by dwinn** [comment]
This has been fixed in the latest release v2018052301
