### ISSUE TITLE
Lightbox close button does not work

### ISSUE THREAD

**Issue by haietza** [turnitin/moodle-mod_turnitintooltwo#429]
Clicking the close text in the lightbox does not work and produces the following error:

Uncaught TypeError: Cannot read property 'close' of undefined at HTMLAnchorElement.onclick

Looks to be in jquery/turnitintooltwo_extra.js and jquery/turnitintooltwo.js:
$.colorbox.close(); return false;

Plugin version 2018031201

**Comment by dwinn** [comment]
Hi @haietza,

Thank you for reporting this. I have been able to replicate it myself so we will look into a fix.

As a work around you can close the Lightbox by clicking in the grey area outside of the modal.

**Comment by dwinn** [comment]
This has been fixed in the latest release v2018052301
