### ISSUE TITLE
v2018031201

### ISSUE THREAD

**Issue by kenneth-hendricks** [turnitin/moodle-mod_turnitintooltwo#430]
Hi All,

http://www.turnitin.com/en_us/support/download-integrations indicates that v2018031201 of this plugin has been released. I was wondering if this repo is going to be updated with these new changes ?

Thanks,
Kenneth

**Comment by kenneth-hendricks** [comment]
Answered my own question when i realised that this was in the develop branch, sorry for any trouble.

**Comment by dwinn** [comment]
Hi @kenneth-hendricks,

We don't advise using the develop branch as it is our developer branch that we merge to before putting together a new release. So it will contains unreleased code that has not been finalised by us. New functionality on the branch could change before release or even be unfinished at that moment in time.

Master is the branch which contains the latest release, but you can also get the latest releast via the releases page. https://github.com/turnitin/moodle-mod_turnitintooltwo/releases
