### ISSUE TITLE
Cannot upgrade from 2016122101 to newer versions

### ISSUE THREAD

**Issue by 6079-Winston-Smith** [turnitin/moodle-mod_turnitintooltwo#438]
I receive a PHP error:

PHP Fatal error:  Maximum execution time of 600 seconds exceeded in E:\\moodlebase\\moodle\\lib\\dml\\mysqli_native_moodle_database.php on line 1079, referer: https://moodle.pembroke.sa.edu.au/admin/index.php?cache=0&confirmplugincheck=0

I have tried many things to get past this error, all without success:
1. Upgrade to PHP 7.1 
2. Upgrade to latest MySQL
3. Upgrade the turnitintool incrementally to 2016122101, but next update fails, as do later ones.
4. Upgrade Moodle first to newer version (from 2.9.2 to 2.9.9, then to 3.0.10) before trying to update the plugin.
5. Tweak many MySQL settings - turn on large tables (this delays the error but does not avoid), increase tmp file size, upgrade all tables to Barracuda; so many little changes I can't remember them all.

I am defeated! Our Moodle will never be updated if I can't get past this error.

**Comment by dwinn** [comment]
Hi @6079-Winston-Smith ,

It sounds like the database upgrade script is timing out.

Could you try adding this line temporarily to the <plugin root>/db/upgrade.php script near the top after the php tag?

```set_time_limit(2000);`

This will increase your maximum execution time for this page and allow you to exceed 600 seconds. This can be removed after the upgrade. If this doesn't work then you may need to edit your php.ini server file to increase the timeout.
