### ISSUE TITLE
Grade entered in Moodle does not sync the grade in Turnitin Feedback Studio

### ISSUE THREAD

**Issue by athchatzi** [turnitin/moodle-mod_turnitintooltwo#446]
This is a significant bug. 
Grades entered on Turnitin Feedback Studio will sync the Moodle grade
however, any change to grades via moodle's interface (say via Quick grading) will not update the grade on TII feedback studio interface.

**Comment by jmcgettrick** [comment]
Sorry, we don't allow grades to come into Turnitin. They have to be set in Feedback Studio.
