### ISSUE TITLE
TurnitinTwo ERROR 

### ISSUE THREAD

**Issue by rs6060** [turnitin/moodle-mod_turnitintooltwo#450]
A tutor has added a TurnitinTwo assignment to his course and after entering up the relevant settings and pressing the SAVE AND RETURN TO COURSE, the tutor is shown the following error:

![turnitinerror](https://user-images.githubusercontent.com/5969938/40911536-ef0d1768-67e6-11e8-88d6-fbd6a962667f.jpg)

The tutor tried to add a Turnitin One activity and this worked fine, and this issue only seems to occur when they attempt to use TurnitinTwo.

**Comment by jmcgettrick** [comment]
Hi, would you be able to retry this with debugging on so that we can see what the error is? It sounds like there is a problem with a setting but without debugging on we won't be able to see it as we can't reproduce any problem like that here.
