### ISSUE TITLE
View digital receipt close button

### ISSUE THREAD

**Issue by S-L-WA** [turnitin/moodle-mod_turnitintooltwo#451]
Hi
When trying to close the Digital Recepit by clicking on "Close" button nothing happened. Closing by ESC or clicking outside of box still works. Checked on chrome / firefox. Error in console: 

> Uncaught TypeError: Cannot read property 'close' of undefined
    at HTMLAnchorElement.onclick (view.php?id=32093:1)

Also, when posting in console $.colorbox it says it's undefined

**Comment by dwinn** [comment]
Hi @S-L-WA,

Which version of the plugin are you using? We fixed this in the latest version v2018052301.

**Comment by rlorenzo** [comment]
@dwinn We have a similar issue, but with the close buttons for "Notify Non-Submitters" and "TurnItIn Message Inbox". The other close buttons work for us.

We are running 2018052301.

**Comment by dwinn** [comment]
Hi @rlorenzo,

Thank you for providing further information and the pull request. We will get this fixed. Would you be able to change the base branch on your pull request to develop? As our process is to test against develop and then release into master. It seems we missed these when we did the changes to the close button in #434.

**Comment by rlorenzo** [comment]
@dwinn I am running into issues running npm install on develop branch.

I get: http://bin-repo.iparadigms.com:80/artifactory/api/npm/am-npm/readable-stream/-/readable-stream-1.0.34.tgz failed, reason: getaddrinfo ENOTFOUND

Then now on master I get this error as well: http://10.64.4.12:4873/is-dotfile/-/is-dotfile-1.0.2.tgz failed, reason: connect ETIMEDOUT

The URLs for these packages seem to be unavailable anymore. Can the npm libraries be updated so we can run gulp to compile the css/js? Or can we provide the patch without compiled js/css?

**Comment by dwinn** [comment]
I am closing this as we have resolved close button issues with our latest release.
