### ISSUE TITLE
Any reference to jQuery related files results in 404 Not found in console

### ISSUE THREAD

**Issue by coriordan** [turnitin/moodle-mod_turnitintooltwo#453]
Using Version 2018052301 on Moodle 3.4.3 and the grader interface does not render. Looking at the console in the browser (Google Chrome) shows that none of the jQuery related files were loaded; all plugin related jQuery files gives the following error:

Failed to load resource: the server responded with a status of 404 (Not Found)

the following files fail to load:
jquery-3.2.1.js 
jquery-ui.js 
jquery.dataTables.js 
jquery.dataTables.css 
jquery.dataTables.plugins.js 
turnitintooltwo.js 
turnitintooltwo_extra.js 
turnitintooltwo_settings.js 
jquery.dataTables.columnFilter.js 
jquery.colorbox.js 
colorbox.css 
jquery.cookie.js 
jqueryui-editable.js 
jqueryui-editable.css 
moment.js 

Is there a workaround?

**Comment by jmcgettrick** [comment]
Most of these are now removed
