### ISSUE TITLE
Fatal error: Cannot redeclare turnitintooltwo_override_repository()

### ISSUE THREAD

**Issue by coriordan** [turnitin/moodle-mod_turnitintooltwo#454]
I've just set up a test instance of Moodle 3.4.3 with only the turnitintooltwo plugin (ver. 2018052301) plugin installed. I'm getting the error below having created a Turnitin activity and attempting to access it:

`Fatal error: Cannot redeclare turnitintooltwo_override_repository() (previously declared in /Users/Cathal/Work/vle/moodle-test/mod/turnitintooltwo/lib.php:1812) in /Users/cathal/Work/vle/moodle-test/mod/turnitintooltwo/lib.php on line 1812`

**Comment by jmcgettrick** [comment]
Closing - Stale issue
