### ISSUE TITLE
Why "Removing old report gen speed note."

### ISSUE THREAD

**Issue by sleitao** [turnitin/moodle-mod_turnitintooltwo#455]
Why was the speed note removed?
Commit: https://github.com/turnitin/moodle-mod_turnitintooltwo/commit/cec1e15d2a9814979c4b5c034187797466baf078#diff-a376b7464fdf4605416fb3eec19b6940

Is it possible to get it back?

**Comment by jmcgettrick** [comment]
It was replaced with https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/develop/lang/en/turnitintooltwo.php#L487
