### ISSUE TITLE
Errors with php7.2 due to new warnings

### ISSUE THREAD

**Issue by ilya-catalyst** [turnitin/moodle-mod_turnitintooltwo#460]
Unit tests for v1migration on are getting error on 
`$this->assertEquals(1,count($v1migration->v1assignment->legacy));`

if you run them with php7.2 due to http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types

**Comment by dwinn** [comment]
Hi @ilya-catalyst,

Thanks for the report. We will make a ticket to fix this and check for any other issues with PHP 7.2.

**Comment by dwinn** [comment]
We have now released your pull request. Thanks for the contribution.
