### ISSUE TITLE
updateavailable function has incorrect hardcoded URL. And shouldn't even be there!

### ISSUE THREAD

**Issue by thepurpleblob** [turnitin/moodle-mod_turnitintooltwo#462]
In mod/turnitintooltwo/lib.php around line 925, the following URL is hardcoded...

https://www.turnitin.com/static/resources/files/moodledirect2_latest.xml

It returns 404 not found. The function fails with masses of XML errors if you have debugging on. 

As an aside, I don't like at all checking for updates in the settings page. Moodle has a mechanism for checking for plugin updates so this is entirely spurious.

**Comment by dwinn** [comment]
Hi @thepurpleblob,

I am seeing this as well so I am looking into why that URL is returning a 404.

From what I can see plugin update checks in Moodle was new in Moodle 2.4 and I think our update check was in place before that time and has stuck around. I can't say we'll remove it as some customers might find it useful, but we'll definitely fix the 404 issue.

**Comment by dwinn** [comment]
I'll have a chat with the team about whether we should remove the check but in the meantime I'm aiming to get a redirect put on that URL as changing it would require a new release and everyone upgrading.

**Comment by thepurpleblob** [comment]
Ok - that's the main thing. Thanks!

**Comment by thepurpleblob** [comment]
Ok thanks. 

I'll probably just comment out the bit in settings.php that calls the upgrade check.

**Comment by dwinn** [comment]
Hi @thepurpleblob,

This has been removed in the latest version v2018082801 in favour of Moodle's functionality.
