### ISSUE TITLE
Possible omission in privacy declaration?

### ISSUE THREAD

**Issue by thepurpleblob** [turnitin/moodle-mod_turnitintooltwo#464]
In the Privacy API declaration a number of fields are declared in link_external_location().  Shouldn't is also declare the actual submission contents/data that is sent to be processed?

**Comment by cwestgarth** [comment]
Hey @thepurpleblob 
Ah yes! We'll add this into our next release. 
Thanks 
Caroline

**Comment by dwinn** [comment]
Hi @thepurpleblob,

This has now been added and released in the latest version - v2019050101.
