### ISSUE TITLE
Pencil icons sit on top of text when window resized 

### ISSUE THREAD

**Issue by troywilliams** [turnitin/moodle-mod_turnitintooltwo#496]
Pencil icons sit on top of text when window resized, screenshot attached. 

![screenshot-2018 11 30-14-13-47](https://user-images.githubusercontent.com/607907/49266778-485ec700-f4bc-11e8-8f05-ae243d83be2e.png)

Plugin in version 2018102601

**Comment by jmcgettrick** [comment]
Duplicate of #583
