### ISSUE TITLE
Email address changes will not be reflected in Turnitin

### ISSUE THREAD

**Issue by jmcgettrick** [turnitin/moodle-mod_turnitintooltwo#52]
If a user's email address is changed in Moodle, this will not reflect in Turnitin. If the user is unlinked and then the email address is changed a new Turnitin user account will be created.

**Comment by rlorenzo** [comment]
This is a major problem for us. We have to manually unlink and then relink a student when their email changes. But that causes unknown consequences on the TurnItIn side. Can you use the Moodle username for an ID instead of email?

**Comment by rlorenzo** [comment]
Just following up that this issue keeps on hitting us and we have to keep on manually re-linking students. We are actually telling students to stop changing their email address, but that isn't realistically possible.

Any idea or road map on a patch?

**Comment by rlorenzo** [comment]
@jmcgettrick  This bug hit us again. Is the correct workaround to unlink and relink the student? Because that's what I have been doing.

Would a good patch be to do that automatically? Is this still a problem with V2 of the plugin?

**Comment by jmcgettrick** [comment]
If a student changes their email address it will only cause a problem if they are unlinked. Once an account has been created for that user and the id stored against their Moodle user id in the Moodle database we don't need their email address. 

It's only when they are unlinked that there is no way of linking them back to the same account. This is due to the initial search to see if the user exists in Turnitin being based on email address as it's a unique identifier. Relinking them will therefore create a new Turnitin user account.

We can merge student accounts if you need a student to still have access to their original account, product support can do that for you.

**Comment by rlorenzo** [comment]
@jmcgettrick Strange, we don't unlink the student. We only attempt to do that step when a student complains that they get the error message about changed email.

How else, besides the admin UI, can a user get unlinked?

**Comment by jmcgettrick** [comment]
There's no other way to unlink them, we only advise it if there is an issue with accessing their account through the API.

**Comment by jmcgettrick** [comment]
Closing as known issues have been moved to the wiki.

https://github.com/turnitin/moodle-mod_turnitintooltwo/wiki/Known-Issues
