### ISSUE TITLE
Upload submissions icon lacks title attribute

### ISSUE THREAD

**Issue by ebithell** [turnitin/moodle-mod_turnitintooltwo#533]
Each row of the submission inbox view has four icons at the right hand end of each row: upload submission, download submission, refresh submission, delete submission. The last three all have a title attribute set which is visible on hover, but the upload icon lacks this attribute.

Adding a `title="Upload submission"` attribute here would improve accessibility for users with screenreaders.

**Comment by jmcgettrick** [comment]
Thanks @ebithell - I've added a title in #534
