### ISSUE TITLE
Turnitin V1 migration error

### ISSUE THREAD

**Issue by carolinefzhang** [turnitin/moodle-mod_turnitintooltwo#540]
I'm trying to migrate V1 to V2 via V1 Migration tab, but I have this error: DataTables warning: table id=migrationTable - Error reading from database

**Comment by CharlotteSpinks** [comment]
Hi @carolinefzhang, thank you for reaching out, our support team will be able to assist you in this instance. You can create a ticket by emailing tiisupport@turnitin.com
