### ISSUE TITLE
$max undefined property error in logs

### ISSUE THREAD

**Issue by aspark21** [turnitin/moodle-mod_turnitintooltwo#544]
Seeing this in Apache logs
Moodle 3.7.1
TII v2019070201

PHP Notice:  Undefined property: stdClass::$max in /path/to/moodle/mod/turnitintooltwo/lib.php on line 1745

**Comment by aspark21** [comment]
Also:
PHP Notice:  Undefined variable: scoreinner in /path/to/moodle/mod/turnitintooltwo/turnitintooltwo_view.class.php on line 1251

**Comment by dwinn** [comment]
Hi @aspark21,

Thanks for the report. We will get this looked at.

**Comment by aruethe2** [comment]
I believe this was fixed by commit 356f3db5136a7780d55d165a4dddd99aeb93fc44.  The issue is still open, just letting you know that you can probably close it.
