### ISSUE TITLE
Header should have full course name instead of site name

### ISSUE THREAD

**Issue by sleitao** [turnitin/moodle-mod_turnitintooltwo#545]
Hi,
Usually Moodle modules have a page heading with the course name (boost theme).
We noticed that tunitintooltwo module prints the site name instead... Is there a reason for that?

To correct it:
mod/tunritintooltwo/view.php line 460 Release v2019070201
```
-       $SITE->fullname
+	$COURSE->fullname
```

Thank you!

**Comment by dwinn** [comment]
Hi @sleitao,

Thanks for the report. This has been fixed and will go out in the next release.

**Comment by sleitao** [comment]
Thanx!
