### ISSUE TITLE
Moodle Instructor Comment not showing

### ISSUE THREAD

**Issue by grantsue** [turnitin/moodle-mod_turnitintooltwo#552]
After finding that the assignment was hidden on the gradebook side and unhiding it, the grades came though to the students but the comments did not. The TurnItIn assignment is a rough draft so they need the instructor's comments. In the layers for the students, it says they have no comments and the graded layer is not listed with a checkbox. 

The professor has 3 sections of this class and he had copied the assignment and all three sections are having an issue. We have added to the comments and it did not help. We have tried to adjust other class' assignment and it worked fine. We feel that hiding the assignment in the gradebook has caused the issue. The gradebook block is not releasing the comments is our best guest.

Thanks for any help!

**Comment by CharlotteSpinks** [comment]
Hi @grantsue, thanks for reporting this issue. Are you able to please log a ticket with our support helpdesk at tiisupport@turnitin.com and they will be able to investigate this further with you.
