### ISSUE TITLE
Wrong parts order after activity duplication

### ISSUE THREAD

**Issue by golenkovm** [turnitin/moodle-mod_turnitintooltwo#555]
Hi team,

When turnitintooltwo activity gets duplicated the order of parts might be different than in original activity.

How to replicate: 
1. Create turnitintooltwo activity with 3 parts (Part 1, Part 2, Part 3).
2. Open it couple of times.
3. Duplicate activity.
4. Check parts order in duplicated activity - sometimes they are created in a wron order (Part 3, Part 2, Part 1 or Part 1, Part 3, Part 2 etc).

It happens because of defult db sorting of part records.
When you open an activity, `gradesupdated` field in `mdl_turnitintooltwo_parts` table gets updated via axaj. Ajax requests might be processed in any order so finally when you select records without specific ordering and relying on db you can get them in different order.

**Comment by jmcgettrick** [comment]
Fixed by #556
