### ISSUE TITLE
The coursecat class is deprecated in Moodle 3.6

### ISSUE THREAD

**Issue by rlorenzo** [turnitin/moodle-mod_turnitintooltwo#558]
In https://tracker.moodle.org/browse/MDL-62742 the class coursecat has been renamed to core_course_category.

Instances that need to be changed are 

- https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/develop/extras.php#L111
- https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/develop/lib.php#L1490

**Comment by rlorenzo** [comment]
Note this is partially fixed in https://github.com/turnitin/moodle-mod_turnitintooltwo/commit/809b930564bebdcacd8dd93283a711185ecf71ef#diff-44376c7e47071c0c82052d33d5f0ef45R330

But old deprecated call still exists in: https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/develop/lib.php#L1490

**Comment by jack-tii** [comment]
This has been fixed in our latest release
