### ISSUE TITLE
Exception - Class 'SoapClient' not found 

### ISSUE THREAD

**Issue by demsley** [turnitin/moodle-mod_turnitintooltwo#561]
Just trying to do a fresh install on a testing server running Moodle 3.6.1

I get the error below when installing using drag and drop installation of plugin and when uploading it via ftp.

 Exception - Class 'SoapClient' not found
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 13 of /mod/turnitintooltwo/sdk/soap.class.php: Error thrown
    line 6 of /mod/turnitintooltwo/sdk/usersoap.class.php: call to require_once()
    line 3 of /mod/turnitintooltwo/sdk/api.class.php: call to require_once()
    line 24 of /mod/turnitintooltwo/turnitintooltwo_comms.class.php: call to require_once()
    line 25 of /mod/turnitintooltwo/turnitintooltwo_assignment.class.php: call to require_once()
    line 29 of /mod/turnitintooltwo/lib.php: call to require_once()
    line 909 of /lib/classes/component.php: call to include_once()
    line 7645 of /lib/moodlelib.php: call to core_component::get_plugin_list_with_file()
    line 1224 of /lib/outputrenderers.php: call to get_plugins_with_function()
    line 462 of /lib/outputrenderers.php: call to core_renderer->header()
    line 208 of /admin/renderer.php: call to plugin_renderer_base->__call()
    line 679 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()

**Comment by jmcgettrick** [comment]
I'm assuming this was because SoapClient wasn't installed.
