### ISSUE TITLE
Improvement on get_suspended_userids

### ISSUE THREAD

**Issue by tuanngocnguyen** [turnitin/moodle-mod_turnitintooltwo#563]
The following usage of get_suspended_userids function:
https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/master/view.php#L424
https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/master/turnitintooltwo_assignment.class.php#L617

Could be improved to use cache:
https://github.com/moodle/moodle/blob/master/lib/accesslib.php#L7537

It is safe to use the cache as it is invalidated once user enrolment is updated in the a course
https://github.com/moodle/moodle/blob/master/lib/enrollib.php#L2109

**Comment by jmcgettrick** [comment]
Thanks @tuanngocnguyen

**Comment by jmcgettrick** [comment]
PR Merged. Thanks!
