### ISSUE TITLE
Non-logged in user receives an uninformative error message

### ISSUE THREAD

**Issue by mronkko** [turnitin/moodle-mod_turnitintooltwo#566]
I have a course that is globally visible without logging in and uses TurnItIn for assignments. The idea is that I want to provide all my materials freely for anyone, but only those uses who are enrolled on the course can submit assignments.

After logging out, When I click on a TurnItIn assignment, I get the following error message:

"turnitintooltwo/Turnitin user creation failed

Message: email - Email should be of the format someuser@example.com

More information about this error"

It appears that the plugin tries to contact TurnItIn API even for non-authenticated user, which naturally fail.

The desired behavior would be to check the authentication status of the user and just display the assignment title and description and an informative text that only students who have registered on the course can submit assignments.

You can see this error in action by visiting the following page:

https://mycourses.aalto.fi/mod/turnitintooltwo/view.php?id=492378

**Comment by CharlotteSpinks** [comment]
Hi @mronkko thanks for reaching out. 
Part of our authentication process is that we require users to have an email address attached to their login, in order to display Turnitin content. We do not currently have in place any method of viewing Turnitin content without being an authenticated/enrolled user of the course/content you are trying to view.

**Comment by mronkko** [comment]
I am not suggesting that the plugin should show any content from Turnitin. What I suggested that when a user is logged in, they are shown the title and description from Moodle and perhaps a message "You need to be logged in to view TurnItIn content". The current error message is not informative and looks like a system error from the users perspective instead of something that appears by design. 

For example, if you look at the behavior of the Moodle's built-in assignment activity, it simply shows the title and description if the user is not logged in:

https://mycourses.aalto.fi/mod/assign/view.php?id=570766

Displaying information this way instead of the current error message would be more preferable.

**Comment by jmcgettrick** [comment]
Fixed by #610

**Comment by mronkko** [comment]
Thanks for fixing the error message. However, this is just a partial solution. @CharlotteSpinks wrote that that there is no way to access TurnItIn data without authentication. What I was suggesting was that the plugin would simply show the assignment description from Moodle database to a) guest users and b) authenticated users that do not have a role on the course.

This would be useful in at least two use cases:

1. Students who are part of my organization want to go through the course materials to assess how much work the course is before they commit to doing the course by signing up
2. Colleagues from other organizations might want to audit my course to get ideas on their own teaching

If I understood the plugins code correctly, the assignment description is written out on lines 909-921 in the following file

https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/047ab749bde8c2d08d629bd7562fd5c2cffe24ab/turnitintooltwo_view.class.php

This seems to just pull data from the Moodle database and could be thus shown to non-logged in users as well. Right?

**Comment by jmcgettrick** [comment]
Got you, added the description in: https://github.com/turnitin/moodle-mod_turnitintooltwo/pull/615
