### ISSUE TITLE
PHP 7.4 Deprecated ternary operators without parentheses

### ISSUE THREAD

**Issue by sharpchi** [turnitin/moodle-mod_turnitintooltwo#569]
On installation I'm getting the following error:
Deprecated: Unparenthesized \`a ? b : c ? d : e\` is deprecated. Use either \`(a ? b : c) ? d : e\` or \`a ? b : (c ? d : e)\` in /var/www/html/moodle38/mod/turnitintooltwo/sdk/soap.class.php on line 218

This is deprecated as of PHP7.4
https://www.php.net/manual/en/migration74.deprecated.php

**Comment by Peterburnett** [comment]
The first PR seems to have incorrect behaviour, due to the ordering. I have submitted a new PR with the second chunk parenthesised.

**Comment by arjenlentz** [comment]
It'd be great to see this merged. It's a tiny and sensible syntax fix.
ping @jmcgettrick

**Comment by thepurpleblob** [comment]
Just a "me too". Annoying problem that should be quick to fix

**Comment by jmcgettrick** [comment]
Fixed in #590
