### ISSUE TITLE
Moodle 3.9 - report generation speed form offset

### ISSUE THREAD

**Issue by aspark21** [turnitin/moodle-mod_turnitintooltwo#572]
Moodle 3.9
Turnitintooltwo master & develop both tested

![Screenshot 2020-06-23 at 15 48 29](https://user-images.githubusercontent.com/4015496/85425445-1961e780-b571-11ea-82b6-102ea575cf64.png)

**Comment by jmcgettrick** [comment]
Fixed by #595
