### ISSUE TITLE
Moodle 3.8.4+ & 3.9: Student view broken

### ISSUE THREAD

**Issue by rlorenzo** [turnitin/moodle-mod_turnitintooltwo#573]
1. Create an TurnItIn assignment
2. Enter student view by logging in as a student.
3. Navigate to a Turnitin assignment that has been submitted and select it.
4. Try to click on any of the icons or to view similarity, nothing works. Only digital receipt works.

I see this JS error on the console that might be related:

> Uncaught TypeError: Cannot read property 'mData' of undefined
    at HTMLTableCellElement.<anonymous> (jquery.dataTables.js:6429)
    at Function.each (jquery-3.4.1.min.js:2)
    at k.fn.init.each (jquery-3.4.1.min.js:2)
    at HTMLTableElement.<anonymous> (jquery.dataTables.js:6426)
    at Function.each (jquery-3.4.1.min.js:2)
    at k.fn.init.each (jquery-3.4.1.min.js:2)
    at k.fn.init.DataTable [as dataTable] (jquery.dataTables.js:6101)
    at HTMLTableElement.<anonymous> (turnitintooltwo-2018102601.js:356)
    at Function.each (jquery-3.4.1.min.js:2)
    at k.fn.init.each (jquery-3.4.1.min.js:2)

**Comment by rlorenzo** [comment]
The broken JS is due to this change in Moodle 3.8.4:

MDL-68343 - Gradebook: Single view: Accessibility issues

This commit specifically:  

The note in the commit is: 

> A <th> that contains no text may result in cells with missing or
> incorrect header information. WAVE advises that we should make a cell
> a <td> rather than a <th> if the cell must remain empty (such as the
> top-left cell in a data table).

Also note that the scope attribute is only valid for <th>

But the way the TurnItIn JS code works is by counting the number of header cells:

https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/985ad326cf809f7e9f592197d8dce5916326e75b/jquery/turnitintooltwo-2018102601.js#L285

But since some of the headers have no text, the headers are actually td not th anymore. So the number of columns differs from what the DataTables JQuery plugin is expecting. Hence the JS error and the broken JS causing problems.

**Comment by CharlotteSpinks** [comment]
Hey @rlorenzo thanks for the PR, this is now in the latest release 2020072201.

**Comment by CharlotteSpinks** [comment]
Hey @rlorenzo I'm not able to recreate this, I can access the reports and click on the icons as expected in the student view, in 3.9. No errors in console. Have you a screen recoding of this in action? 
Thanks!

**Comment by rlorenzo** [comment]
@CharlotteSpinks You cannot reproduce this because it was merged into the latest release here: https://github.com/turnitin/moodle-mod_turnitintooltwo/commit/dee9d9f204bf2c0338aa41ff22f388e618fd9ab6
