### ISSUE TITLE
Link to Similarity Report in Turnitin not working for students

### ISSUE THREAD

**Issue by coriordan** [turnitin/moodle-mod_turnitintooltwo#582]
Hi,

We recently upgraded to Moodle 3.9. When a student accesses their Turnitin submission within the plugin, the link access the similarity report is unresponsive, i.e. you can click on the submission title, but it will not bring up the Turnitin Feedback Studio.  The option to display originality report to students is enabled.

Moodle version: 20200713
Turnitin V2 plugin version: 2019070201

regards,
Cathal.

**Comment by CharlotteSpinks** [comment]
Hey @coriordan Could you please install the latest version of the Turnitin plugin where a fix has been merged for this. 2020072201
Thanks, Lottie

**Comment by coriordan** [comment]
Thanks for your help Lottie. Much appreciated.

best regards,
Cathal.
