### ISSUE TITLE
some DB schema misaligned fields

### ISSUE THREAD

**Issue by yao9394** [turnitin/moodle-mod_turnitintooltwo#584]
php admin/cli/check_database_schema.php

turnitintooltwo
 * column 'institution_check' has default 'NULL', expected '0' (I)
 * column 'needs_updating' should allow NULL (I)
 * column 'needs_updating' length is 4, expected at least 10 (I)
-------------------------------------------------------------------------------
turnitintooltwo_parts
 * column 'unanon' length is 4, expected at least 10 (I)
 * column 'submitted' length is 4, expected at least 10 (I)

**Comment by jmcgettrick** [comment]
Thanks @yao9394 - we'll get this looked at.

**Comment by yao9394** [comment]
We can close this as this is a duplicate of https://github.com/turnitin/moodle-mod_turnitintooltwo/issues/553
