### ISSUE TITLE
Uncaught TypeError: col is undefined

### ISSUE THREAD

**Issue by haietza** [turnitin/moodle-mod_turnitintooltwo#586]
Students can't click on the originality score nor the grade and be delivered to Feedback Studio or the Originality Report, respectively (they seem to work as they always have for teacher role). They show as hyperlinks, but clicking does nothing. Clicking on the submission title also does nothing.

The console displays "Uncaught TypeError: col is undefined" from the jquery.dataTables.js file, line 6429.

**Comment by CharlotteSpinks** [comment]
Hey @haietza Could you please let me know what version of the plugin you are using? As we are aware that this has been fixed in version 2020072201.

**Comment by haietza** [comment]
@CharlotteSpinks We were using an older version. I didn't see an issue for it, so thank you for letting me know about the update!
