### ISSUE TITLE
Plagiarism Plugin assignments not being submitted

### ISSUE THREAD

**Issue by mkpelletier** [turnitin/moodle-mod_turnitintooltwo#59]
Hello All,

Since the new update yesterday, (2015040111), we are getting the following error from the plagiarism plugin:

Turnitin has returned an error with your submission: Coding error detected, it must be fixed by a programmer: Could not load preference popup_provider_mod_turnitintooltwo_submission_permitted. Make sure the component and name you supplied to message_send() are valid.

Our Plagiarism Plugin version is 2015040110.  Our Moodle version is: 2014111006.09 (2.8.6+)

**Comment by jmcgettrick** [comment]
Hi Mathieu,

We've seen this affect another user recently, default settings for message providers aren't being set for some reason during upgrades. I can't replicate this but it looks to be something that occurs during an upgrade.

You can fix this by going to Plugins > Message outputs > Default message outputs and ensure values are set for:

Turnitin Assignment Digital Receipt notifications
Turnitin Plagiarism Plugin Digital Receipt notifications
Turnitin Assignment Non Submitter notifications

And then click “Save changes”.

Let us know how that goes.

Regards

John

**Comment by mkpelletier** [comment]
Hello John,
Thanks for that.  That seems to have done the trick!  Thanks for all the hard work!
