### ISSUE TITLE
Deprecated: implode(): Passing glue string after array is deprecated.

### ISSUE THREAD

**Issue by dmitriim** [turnitin/moodle-mod_turnitintooltwo#591]
When running in PHP7.4 we are getting following error.

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/site/mod/turnitintooltwo/turnitintooltwo_assignment.class.php on line 1933

**Comment by jmcgettrick** [comment]
Fixed by #593
