### ISSUE TITLE
Moodle 3.5/3.6 support

### ISSUE THREAD

**Issue by anieminen** [turnitin/moodle-mod_turnitintooltwo#603]
Hi,

Are Moodle 3.5 or 3.6 still supported in the latest version of the plugin? It doesn't require Moodle >= 3.7 according to version.php, but in [the plugins database](https://moodle.org/plugins/pluginversions.php?plugin=mod_turnitintooltwo) 3.7 is the minimum version.

**Comment by CharlotteSpinks** [comment]
Hi @anieminen we try to stay in line with the versions moodle support here https://docs.moodle.org/dev/Releases#Version_support support for 3.6 has been dropped, 3.5 is a LTS version so will be supported but we expect most people will be on 3.7 at least by now which was released May 2019.
