### ISSUE TITLE
Error when trying to restore

### ISSUE THREAD

**Issue by ghost** [turnitin/moodle-mod_turnitintooltwo#634]
Hello, When am trying to restore i get the following error causing the whole restore procedure to fail

![error](https://user-images.githubusercontent.com/1250521/136800027-fb5e7e63-1795-44de-bde0-4a75ba0e722d.png)

Any way to fix this?

Moodle Version: 3.11.2+ (Build: 20210805)
Plugin Version: 2021060801

**Comment by angemmell** [comment]
Moodle 3.9. We upgraded to the Moodle direct v2 v2021060801 in mid December 2021 and began to receiving feedback on this error when trying to restore a unit.
The end date enabled in the class is within the 1 year grange. 
Prior to upgrading to the new plugin we did not experience any issues with restoring units. Has something changed in the plugin that would affect how the restore works?

**Comment by kabalin** [comment]
I suppose, if restore process will follow "Use new assignments dates" logic (similar to one used in course rest), this won't be the issue. If you accept PR with this change, I can submit a patch (🏓 @dwinn).
