### ISSUE TITLE
Dot in the file name

### ISSUE THREAD

**Issue by Dextirpe** [turnitin/moodle-mod_turnitintooltwo#67]
It's a known issue?
There should not be more than one dot (the dot just before the file extension such as .pdf) in the file name. Moodle cron is frozen. Its a critical issue!

**Comment by jmcgettrick** [comment]
Hi, we can't reproduce this issue. Which version of the plugin are you using?

**Comment by Dextirpe** [comment]
Sorry, error is in "Turnitin Plagiarism plugin for Moodle". I use 2015040110 (last version)
I have Moodle realise 2.8.9+ (Build: 20151110)

I think these lines are wrong if filename have more than one dot. I don't know if fixing these lines solve the error but I think they're wrong.
../moodle/plagiarism/turnitin/lib.php at line 2516:
// Read the stored file/content into a temp file for submitting.
        $submission_title = explode('.', $title);

        $file_string = array(
            $submission_title[0], //wrong!!
            $cm->id
        );

**Comment by jmcgettrick** [comment]
Hi, I can't reproduce the issue. My initial thought was that it would be to do with "Allow submission of any file type?" being set to "No" but it works for me with either yes or no set.

Are you get a corresponding error in the API logs?

**Comment by Dextirpe** [comment]
I set "Allow submission of any file type?" to "No".
Error is in "Turnitin Plagiarism plugin for Moodle" (moodle-plagiarism_turnitin). Perhaps the issue should be moved to https://github.com/turnitin/moodle-plagiarism_turnitin/issues.

Cron error log:

    Execute scheduled task: Processament en segon pla dels esdeveniments
    ... started 08:07:37. Current memory use 4.7MB.
    ... used 40 dbqueries
    ... used 125.96516895294 seconds
    Scheduled task failed: Processament en segon pla dels esdeveniments,S'ha produït un error en escriure a la base de dades.
    Debug info:
    server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
    UPDATE est_events_queue_handlers SET errormessage = $1,timemodified = $2,status = $3 WHERE id=$4
    [array (
      'errormessage' => 'Handler function of component plagiarism_turnitin: s:39:"plagiarism_turnitin_event_file_uploaded"; threw exception :S\'ha produït un error en escriure a la base de dades.
    * line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
    * line 1131 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    * line 1171 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->update_record_raw()
    * line 2655 of /plagiarism/turnitin/lib.php: call to pgsql_native_moodle_database->update_record()
    * line 2164 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->tii_submission()
    * line 2705 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->event_handler()
    * line ? of unknownfile: call to plagiarism_turnitin_event_file_uploaded()
    * line 299 of /lib/eventslib.php: call to call_user_func()
    * line 343 of /lib/eventslib.php: call to events_dispatch()
    * line 450 of /lib/eventslib.php: call to events_process_queued_handler()
    * line 45 of /lib/classes/task/events_cron_task.php: call to events_cron()
    * line 74 of /lib/cronlib.php: call to core\\task\\events_cron_task->execute()
    * line 61 of /admin/cli/cron.php: call to cron_run()
    server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
    UPDATE est_plagiarism_turnitin_files SET attempt = $1,cm = $2,userid = $3,identifier = $4,statuscode = $5,lastmodified = $6,submissiontype = $7,errorcode = $8,errormsg = $9 WHERE id=$10
    [array (
      \'attempt\' => 2,
      \'cm\' => \'176637\',
      \'userid\' => \'1553\',
      \'identifier\' => \'0966514e3a14cef0dc526e84c277435745cf355f\',
      \'statuscode\' => \'error\',
      \'lastmodified\' => 1448867383,
      \'submissiontype\' => \'file\',
      \'errorcode\' => 0,
      \'errormsg\' => \'S\\\\&#39;ha produït un error amb el teu lliurament: S\\\'ha produït un error en escriure a la base de dades.\',
      0 => \'806\',
    )]',
      'timemodified' => 1448867383,
      'status' => 3,
      0 => '199073',
    )]
    Backtrace:
    * line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
    * line 1131 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    * line 1171 of /lib/dml/pgsql_native_moodle_database.php: call to     pgsql_native_moodle_database->update_record_raw()
    * line 364 of /lib/eventslib.php: call to pgsql_native_moodle_database->update_record()
    * line 450 of /lib/eventslib.php: call to events_process_queued_handler()
    * line 45 of /lib/classes/task/events_cron_task.php: call to events_cron()
    * line 74 of /lib/cronlib.php: call to core\task\events_cron_task->execute()
    * line 61 of /admin/cli/cron.php: call to cron_run()

**Comment by Dextirpe** [comment]
Aalto University have similar problem and is reported at "Student Frequently Asked Questions and Known issues": https://wiki.aalto.fi/display/turnitin/Turnitin+support

**Comment by jmcgettrick** [comment]
Hi, do you have the name of the filename being sent to Turnitin that is failing? If you look in the API logs in Site Administration > Plugins > Activity Modules > Turnitin Assignment 2 > Logs you should see a submit request that looks something like: 

{noformat}
------------------------------------------------------------
2015-12-16 14:37:15 +0000 - INFO -->
------------------------------------------------------------
POST #########/api/lti/1p0/upload/submit
Array
(
    [lti_version] => LTI-1p0
    [resource_link_id] => #########
    [lis_person_sourcedid] => #########
    [lis_lineitem_sourcedid] => #########
    [roles] => Instructor
    [custom_source] => 12
    [custom_submission_title] => Test
    [custom_submission_author] => #########
    [custom_xmlresponse] => 1
    [custom_widemode] => 0
    [lang] => en_us
    [custom_integration_version] => #########
    [custom_plugin_version] => #########
    [oauth_nonce] => #########
    [oauth_timestamp] => #########
    [oauth_consumer_key] => #########
    [custom_submission_data] => CURLFile Object
        (
            [name] => #########Moodle_Student1_Test_24_1574027424.docx
            [mime] => application/vnd.openxmlformats-officedocument.wordprocessingml.document; charset=binary
        )
)
------------------------------------------------------------
{noformat}

**Comment by jmcgettrick** [comment]
We have ensured filenames are UTF-8 encoded in 2016011101 and are using Moodle's clean_param function to escape filenames.
