### ISSUE TITLE
Deprecated SOAP warning during installation

### ISSUE THREAD

**Issue by cafranks** [turnitin/moodle-mod_turnitintooltwo#685]
Plugin version 2023032701

During a new installation, the following warning is displayed:

Deprecated: Return type of Soap::__doRequest($request, $location, $action, $version, $one_way = null) should either be compatible with SoapClient::__doRequest(string $request, string $location, string $action, int $version, bool $oneWay = false): ?string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/mod/turnitintooltwo/sdk/soap.class.php on line 286

**Comment by timmartinez** [comment]
We're getting it too. It's really making things fun on our development server.

**Comment by srobotta** [comment]
This warning does not only appear when installing, but also e.g. on the backup course page. We are on PHP8.1 (might be no warning at lower versions of PHP).

**Comment by haietza** [comment]
We are preparing a server for 8.1 in December and are also seeing this error. Any ETA on when a fix will be pushed?

**Comment by stopfstedt** [comment]
+1. 

PHP 8.0 EOL'ed a year ago, and security support ends in 5 days from now. 
Can we please get a new release that ships this fix before this happens?

**Comment by aspark21** [comment]
Log it as a ticket via Turnitin support & then contact your account manager.

Tell them you won’t renew your license if they don’t fix it, that’ll wake them up. 

They’re planning on making this as broken as possible to force you to move onto the LTI integration.

Being a monopoly wasn’t enough…

**Comment by danmarsden** [comment]
LTI won't be ready until at least Moodle 4.4 release but I've also sent a few emails via the back-channel to folks at Turnitin to see if we can get some traction on some of the open issues in the plagiarism and mod_turnitintooltwo Moodle plugins...

but yes - log a ticket via the turnitin support channel is the right "official" process.

**Comment by jack-tii** [comment]
Thanks for reporting this. We have a fix for this on develop, so closing this issue.

**Comment by countingpine** [comment]
For posterity, there were two commits made to fix this in the [commit history](https://github.com/turnitin/moodle-mod_turnitintooltwo/commits/master/sdk/soap.class.php)

https://github.com/turnitin/moodle-mod_turnitintooltwo/commit/c0915a0a33ee777e8fffa7dc9ac11f542c6e6d39 (Sep 2023) adds the `#[\ReturnTypeWillChange]` attribute.
https://github.com/turnitin/moodle-mod_turnitintooltwo/commit/9ba7032a71c8b776318accac2144def20a6ddc4e (Jul 2024) swaps out the attribute for a `?string` return type (as hinted by the original deprecation warning).
