### ISSUE TITLE
"Undefined variable: coursetype" PHP warning when resetting mod_turnitintooltwo

### ISSUE THREAD

**Issue by weilai-irl** [turnitin/moodle-mod_turnitintooltwo#691]
When resetting a course, if the reset option for mod_turnitintooltwo is turned on, it would throw the following PHP warning:

Notice: Undefined variable: coursetype in /opt/vhosts/vle.itsligo.ie/www/mod/turnitintooltwo/turnitintooltwo_assignment.class.php on line 380

The line throwing the warning is at https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/05d468d98278f6ffe3af74f5a4c960925a968c7f/turnitintooltwo_assignment.class.php#L380, and variable `coursetype` is indeed undefined in the function.

Moodle version 4.1.5, plugin version 2023032701.

**Comment by simmonsgc** [comment]
In testing turnitintooltwo plugin version 2024032901 on Moodle version 4.3.5+ (Build: 20240614) today, I received similar warning:

Warning: Undefined variable $coursetype in /var/www/[asulearn-test.appstate.edu/mod/turnitintooltwo/turnitintooltwo_assignment.class.php](http://asulearn-test.appstate.edu/mod/turnitintooltwo/turnitintooltwo_assignment.class.php) on line_ 380

To recreate:

- Create a new blank course
- Add a Turnitin Assignment via the plugin
- Upon 'Save and return to course' warning is observed

**Comment by jack-tii** [comment]
Thanks for the report, thisis now fixed in the latest version of the plugin
