### ISSUE TITLE
V2 not supporting moodle/course:view permission

### ISSUE THREAD

**Issue by mike-wilson-uk** [turnitin/moodle-mod_turnitintooltwo#7]
We have a custom role which support staff use to administer Moodle courses (without having full site admin rights). 

In other Moodle activities the moodle/course:view permission (View courses without participation) set to allow prevents these staff from appearing as participants in the course but will allow them to administer course content (if the additional permissions are set).

Unfortunately Turnitin V2 assignment doesn't honour the "View courses without participation" permission. Our support staff are appearing as Turnitin Tutors and Turnitin Students in V2 activities (which is confusing for lecturers).

Settings for custom role:

View courses without participation - ALLOW
moodle/course:view

Add Turnitin Tool Activity - ALLOW
mod/turnitintooltwo:addinstance

Grade Turnitin Tool Assignments - ALLOW
mod/turnitintooltwo:grade

Read Turnitin Tool Assignments - ALLOW
mod/turnitintooltwo:read

Submit to Turnitin Tool Assignments - ALLOW
mod/turnitintooltwo:submit

View Turnitin Tool Assignments - ALLOW
mod/turnitintooltwo:view

**Comment by jmcgettrick** [comment]
Hi Mike, unfortunately Turnitin doesn't support non-participating roles in classes.

We currently take our list of students from who is able to submit and our list of teachers from who is able to grade. We could remove users who are able to grade from our list of students but they would still be enrolled as instructors in Turnitin if they accessed any originality reports through the Document Viewer.

**Comment by mike-wilson-uk** [comment]
Hi John, the main annoyance for lecturers seems to be that admin staff appear in their list of students so removing users who are able to grade from the list of students would be really useful.

Thanks for coming back to me so quickly, really appreciated it.

**Comment by aspark21** [comment]
+1

**Comment by chadberg** [comment]
+1 Will try removing grading capabilities from admin staff in their default roles.

**Comment by jmcgettrick** [comment]
Closing, as this isn't possible with Turnitin's workflow.
