### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by aspark21** [turnitin/moodle-mod_turnitintooltwo#70]
Moodle 3.0 Stable
TII2 v2015040111

There is a caching issue whereby if an assignment has previously been visited, the assignment remains stuck on this loading screen. We have done a Purge All Caches at Site level but this requires each end user to clear their own browser which is not appropriate / scalable. Seems to have occured following the update from v2015040109

![image001-2](https://cloud.githubusercontent.com/assets/4015496/11693790/c11b147c-9e9e-11e5-9fc1-75ec32b99f8c.jpg)

**Comment by jmcgettrick** [comment]
Hi, is there an error occuring?

If you enable Moodle debugging does this show anything unexpected being returned by the Ajax calls?

**Comment by aspark21** [comment]
Hi John,

As far as I can remember there wasn't any error's in the chrome console when accessing from an affected browser. Not seeing anything in the error logs

**Comment by jmcgettrick** [comment]
Hi @aspark21, is this still occuring? 

If so can you contact support and provide us with a login? Can you also try enabling full Moodle debugging and give us the response to the ajax calls fired when the page first loads?
