### ISSUE TITLE
Maximum grade set to 0 and Grade Display set to Percentage causing Divided by 0 problem

### ISSUE THREAD

**Issue by wooyunlong** [turnitin/moodle-mod_turnitintooltwo#714]
**Description**
There is a potential division by zero error in the plugin, occurring when the Maximum Grade is set to 0 and the Grade Display is set to Percentage.

This issue leads to an error message in the Submission Inbox: "There was an error when trying to get submissions for this assignment from Turnitin," preventing the listing of all submissions. Interestingly, this error message mirrors the issue that the "Percentage grades now display in the assignment inbox" bug fix aimed to address.

I suspect the issue stems from the $submissiongrade calculation in turnitintooltwo_view.class.php.

**Steps to Reproduce**
1. Create a Turnitin assignment, set Grade Display to "Percentage," and set an Assignment Part's maxmarks to 0. Save.
2. Go to the Turnitin assignment, select the assignment part, and observe the table that usually displays entries. If the issue is replicated, an error will be shown instead of displaying the students and their submissions.

**Expected Behavior**
The system should gracefully handle cases where maxmarks is set to 0. Ideally, it should either prevent setting maxmarks to 0 or properly manage the grade calculation in such scenarios, possibly by setting the grade to a default value or displaying a meaningful error message.

**Actual Behavior**
When maxmarks is set to 0 and Grade Display is set to Percentage, an error message stating "There was an error when trying to get submissions for this assignment from Turnitin" appears, with no submissions being displayed.

**Environment**
Moodle version: 4.1 Stable (Build: 20231222)
Turnitin Plugin version: v2023032701
PHP version: 8.1.21

**Comment by jack-tii** [comment]
Thanks for bringing this to our attention. We now have a fix for this which will go out in our next release.
