### ISSUE TITLE
Export to Excel and Export to Original format buttons no longer work (2024020601)

### ISSUE THREAD

**Issue by jflet1** [turnitin/moodle-mod_turnitintooltwo#717]
Upgraded to the latest version of this plugin recently. Since the update some of the buttons in the Submission inbox interface no longer work (Export to Excel, Export to Original format, and the download and refresh buttons in the table alongside each submission). 

With the major caveat that I know nothing of developing Moodle plugins, I've noticed the file in jquery/turnitintooltwo-2024020601.js has been updated. For example Line 1170 has `on(function () {`, I'm assuming it should read something like `on("click", function () {` instead to re-bind the event.

**Comment by carl-hostrander** [comment]
@jflet1 - Yes we are aware of this and will be releasing a fix for this within the next week or two.
