### ISSUE TITLE
Improvement: Change lastname, firstname display order in list of enrolled Turnitin Students/Teachers

### ISSUE THREAD

**Issue by sleitao** [turnitin/moodle-mod_turnitintooltwo#72]
Some teachers complain that although they have in Moodle the students' name display order as 'firstname, lastname', in Turnitin they have it 'lastname, firstname'. It would be nice if Turnitin module followed Moodle settings. This is just a suggestion for an improvement... Thanks

**Comment by jmcgettrick** [comment]
@junwan6 has provided a pull request https://github.com/turnitin/moodle-mod_turnitintooltwo/pull/168 which we'll get in the plugin soon.

**Comment by dwinn** [comment]
This has now been fixed in the latest release v2016072601.
