### ISSUE TITLE
reference to unknown image

### ISSUE THREAD

**Issue by Syxton** [turnitin/moodle-mod_turnitintooltwo#721]
turnitintooltwo_view.class.php  ~line 1192 references a file that doesn't exist

$OUTPUT->pix_icon('icon-sml', get_string('submittoturnitin', 'turnitintooltwo')

There is no icon-sml.png in the directory and so a broken image is shown.

**Comment by aspark21** [comment]
Fix is in #716

**Comment by aspark21** [comment]
Fixed by https://github.com/turnitin/moodle-mod_turnitintooltwo/commit/7edd1fad62bff63597006f0b620cf9903a2ce73e
Can be closed
