### ISSUE TITLE
"Calling current() on an object" deprecation warning

### ISSUE THREAD

**Issue by simmonsgc** [turnitin/moodle-mod_turnitintooltwo#732]
In testing turnitintooltwo plugin version 2024032901 on Moodle version 4.3.5+ (Build: 20240614) today, I received a deprecation warning:

Deprecated: current(): Calling current() on an object is deprecated in /var/www/asulearn-test.appstate.edu/mod/turnitintooltwo/lib.php on line 254

Steps to recreate:

- Turn editing on
- Add and activity or resource
- In chooser, select Turnitin Assignment
- Make settings for Assignment (defaults are fine)
- Click 'Save and return to course'
- Observe error

**Comment by steveorulez** [comment]
Hello, any news on this?
we have the same problem on moodle 4.3.5+ and php 8.2

christian

**Comment by aspark21** [comment]
Fixed by #746

**Comment by jack-tii** [comment]
Thanks for bringing this to our attention! This has now been resolved on or develop branch.
