### ISSUE TITLE
Links do not get updated after Class Migration is used

### ISSUE THREAD

**Issue by kmccarthy327** [turnitin/moodle-mod_turnitintooltwo#83]
When the Class Migration tool is used, it converts the old turnitintool assignment to a turnitintooltwo assignment within the Moodle course.  But what it does not do is update any links put into Page Activities or Section Descriptions that have the link to that activity in it. 

Example:
Original Link:
http://site/mod/turnitintool/view.php?id=12345

Gets converted to:
http://site/mod/turnitintooltwo/view.php?id=54321

All the links that referenced the original link in the course still point to original link.

**Comment by jmcgettrick** [comment]
We aren't going to be able to fix this as those fields are free text and added by users. I'm assuming there are other places these could show up as well.
