### ISSUE TITLE
Nonce already used errors

### ISSUE THREAD

**Issue by josefbarrera** [turnitin/moodle-mod_turnitintooltwo#85]
We have a queuing system in place where multiple queue workers may simultaneously try to contact turnitin. We are getting many  "Nonce already used" errors because the _getNonce function in sdk/oauthsimple.class.php cannot handle concurrent processes and it generates the same nonce for two processes calling it at the same time.

I will submit a pull request with our fix for this.

**Comment by joebaba** [comment]
Here is the pull request:

https://github.com/turnitin/moodle-mod_turnitintooltwo/pull/86

Thank you

**Comment by mhughes2k** [comment]
We've started seeing this as well:
<img width="1435" alt="tiinonceissue" src="https://cloud.githubusercontent.com/assets/694841/12822369/a64b3c10-cb5f-11e5-98bf-5348f4dcadff.png">

**Comment by paolooprandi** [comment]
Try the fix and report back if it is successful. Its very simple and we would like to see it in core.

**Comment by jmcgettrick** [comment]
Released in v2016011105
