### ISSUE TITLE
Late submissions that are not late

### ISSUE THREAD

**Issue by sk-unikent** [turnitin/moodle-mod_turnitintooltwo#91]
Hey,

If an assignment is set to not allow submissions past, for example, 14:00 and a user submits at 13:59, and the file takes longer than 1 minute to upload from Moodle to Turnitin (the Turnitin UK API is VERY slow) the submission either fails or is marked as late, despite the file being uploaded in time.

I don't think the time Turnitin receives the file should be used as the submission time, it should be the time the file was received Moodle side should it not?

Thanks!
Sky

**Comment by cwestgarth** [comment]
Hey @sk-unikent, 

The change which you are proposing will need to be something which is introduced across all of our integrations for consistency. I think the best avenue to submit your suggestion is via UserVoice. If you aren't familiar with UserVoice, there are instructions of how to find it here:
http://turnitin.com/en_us/resources/blog/424-product/2040-roadmap-and-release-notes

Thank you 

Caroline Westgarth
